Descriptor: &desc
  Ultra>IMAP Ultra-Energy (IMAP-Ultra) Energetic Neutral Atom Imager
TEXT: &txt >
  Ultra captures images of very energetic neutral atoms, particularly hydrogen (H) atoms,
  produced in the solar system at the heliosheath, the region where the solar wind slows,
  compresses, and becomes much hotter as it meets the interstellar medium (ISM).
  The instrument also measures the distribution of solar wind electrons and protons, and
  the magnetic field. See https://imap.princeton.edu/instruments/ultra for more details.

imap_ultra_l1b_45sensor-de:
    Descriptor: 45sensor-de
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_DE>Level-1B Direct Events
    Logical_source: imap_ultra_l1b_45sensor-de
    Logical_source_description: IMAP-Ultra Instrument Level-1B Direct Event Data.

imap_ultra_l1b_90sensor-de:
    Descriptor: 90sensor-de
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_DE>Level-1B Direct Events
    Logical_source: imap_ultra_l1b_90sensor-de
    Logical_source_description: IMAP-Ultra Instrument Level-1B Direct Event Data.

imap_ultra_l1b_45sensor-extendedspin:
    Descriptor: 45sensor-extendedspin
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_Extended-Spin>Level-1B Extended Spin
    Logical_source: imap_ultra_l1b_45sensor-extendedspin
    Logical_source_description: IMAP-Ultra Instrument Level-1B Extended Spin Data.

imap_ultra_l1b_90sensor-extendedspin:
    Descriptor: 90sensor-extendedspin
    TEXT: *txt
    Data_type: L1B_Extended-Spin>Level-1B Extended Spin
    Logical_source: imap_ultra_l1b_90sensor-extendedspin
    Logical_source_description: IMAP-Ultra Instrument Level-1B Extended Spin Data.

imap_ultra_l1b_45sensor-cullingmask:
    Descriptor: 45sensor-cullingmask
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_Culling-Mask>Level-1B Culling Mask
    Logical_source: imap_ultra_l1b_45sensor-cullingmask
    Logical_source_description: IMAP-Ultra Instrument Level-1B Culling Mask Data.

imap_ultra_l1b_90sensor-cullingmask:
    Descriptor: 90sensor-cullingmask
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_Culling-Mask>Level-1B Culling Mask
    Logical_source: imap_ultra_l1b_90sensor-cullingmask
    Logical_source_description: IMAP-Ultra Instrument Level-1B Culling Mask Data.

imap_ultra_l1b_45sensor-badtimes:
    Descriptor: 45sensor-badtimes
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_Badtimes>Level-1B Badtimes
    Logical_source: imap_ultra_l1b_45sensor-badtimes
    Logical_source_description: IMAP-Ultra Instrument Level-1B Badtimes Data.

imap_ultra_l1b_90sensor-badtimes:
    Descriptor: 90sensor-badtimes
    TEXT: *txt
    Data_level: 1B
    Data_type: L1B_Badtimes>Level-1B Badtimes
    Logical_source: imap_ultra_l1b_90sensor-badtimes
    Logical_source_description: IMAP-Ultra Instrument Level-1B Badtimes Data.

imap_ultra_l1c_45sensor-pset-exposure:
    Descriptor: 45sensor-pset-exposure
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Exposure>Level-1C Exposure
    Logical_source: imap_ultra_l1c_45sensor-pset-exposure
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Exposure Data.

imap_ultra_l1c_90sensor-pset-exposure:
    Descriptor: 90sensor-pset-exposure
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Exposure>Level-1C Exposure
    Logical_source: imap_ultra_l1c_90sensor-pset-exposure
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Exposure Data.

imap_ultra_l1c_45sensor-pset-sensitivity:
    Descriptor: 45sensor-pset-sensitivity
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Sensitivity
    Logical_source: imap_ultra_l1c_45sensor-pset-sensitivity
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Sensitivity Data.

imap_ultra_l1c_90sensor-pset-sensitivity:
    Descriptor: 90sensor-pset-sensitivity
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Sensitivity
    Logical_source: imap_ultra_l1c_90sensor-pset-sensitivity
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Sensitivity Data.

imap_ultra_l1c_45sensor-pset-counts:
    Descriptor: 45sensor-pset-counts
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Counts
    Logical_source: imap_ultra_l1c_45sensor-pset-counts
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Counts Data.

imap_ultra_l1c_90sensor-pset-counts:
    Descriptor: 90sensor-pset-counts
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Counts
    Logical_source: imap_ultra_l1c_90sensor-pset-counts
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Counts Data.

imap_ultra_l1c_45sensor-pset-backgroundrate:
    Descriptor: 45sensor-pset-backgroundrate
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Background Rate
    Logical_source: imap_ultra_l1c_45sensor-pset-backgroundrate
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Background Rate Data.

imap_ultra_l1c_90sensor-pset-backgroundrate:
    Descriptor: 90sensor-pset-backgroundrate
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Background Rate
    Logical_source: imap_ultra_l1c_90sensor-pset-backgroundrate
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Background Rate Data.

imap_ultra_l1c_45sensor-histogram:
    Descriptor: 45sensor-histogram
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Histogram
    Logical_source: imap_ultra_l1c_45sensor-histogram
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Histogram Data.

imap_ultra_l1c_90sensor-histogram:
    Descriptor: 90sensor-histogram
    TEXT: *txt
    Data_level: 1C
    Data_type: L1C_Sensitivity>Level-1C Histogram
    Logical_source: imap_ultra_l1c_90sensor-histogram
    Logical_source_description: IMAP-Ultra Instrument Level-1C Pointing Set Grid Histogram Data.
