# ----------------------------- Useful variables -----------------------------
uint8_fillval: &uint8_fillval 255
uint32_fillval: &uint32_fillval 4294967295
real_fillval: &real_fillval -1.0e+31

min_int: &min_int -9223372036854775808
max_int: &max_int 9223372036854775807

# --------------------------- Default attributes -----------------------------
energy_attrs: &energy_default
  CATDESC: Geometric mean energy per nucleon
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Characteristic
  DISPLAY_TYPE: time_series
  FIELDNAM: Energy Table
  FILLVAL: *real_fillval
  FORMAT: F12.6
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

# ------------------------------- Coordinates -------------------------------
epoch:
  DELTA_MINUS_VAR: epoch_delta_minus
  DELTA_PLUS_VAR: epoch_delta_plus

epoch_delta_minus:
  CATDESC: Time from acquisition start to acquisition center
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal,Qualifier:Uncertainty
  FIELDNAM: epoch delta minus
  FILLVAL: *min_int
  FORMAT: I19
  LABLAXIS: Epoch Delta Minus
  SCALETYP: linear
  UNITS: ns
  VALIDMAX: 128000000000
  VALIDMIN: 0
  VAR_TYPE: support_data

epoch_delta_plus:
  CATDESC: Time from acquisition center to acquisition end
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal,Qualifier:Uncertainty
  FIELDNAM: epoch delta plus
  FILLVAL: *min_int
  FORMAT: I19
  LABLAXIS: Epoch Delta Plus
  SCALETYP: linear
  UNITS: ns
  VALIDMAX: 128000000000
  VALIDMIN: 0
  VAR_TYPE: support_data

energy_cno:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for CNO
  DELTA_MINUS_VAR: energy_cno_minus
  DELTA_PLUS_VAR: energy_cno_plus
  FIELDNAM: CNO Energy

energy_fe:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for Fe
  DELTA_MINUS_VAR: energy_fe_minus
  DELTA_PLUS_VAR: energy_fe_plus
  FIELDNAM: Fe Energy

energy_h:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for H
  DELTA_MINUS_VAR: energy_h_minus
  DELTA_PLUS_VAR: energy_h_plus
  FIELDNAM: H Energy

energy_he3he4:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for He3+He4
  DELTA_MINUS_VAR: energy_he3he4_minus
  DELTA_PLUS_VAR: energy_he3he4_plus
  FIELDNAM: He3+He4 Energy

energy_c:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for C
  DELTA_MINUS_VAR: energy_c_minus
  DELTA_PLUS_VAR: energy_c_plus
  FIELDNAM: C Energy

energy_he3:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for He3
  DELTA_MINUS_VAR: energy_he3_minus
  DELTA_PLUS_VAR: energy_he3_plus
  FIELDNAM: He3 Energy

energy_he4:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for He4
  DELTA_MINUS_VAR: energy_he4_minus
  DELTA_PLUS_VAR: energy_he4_plus
  FIELDNAM: He4 Energy

energy_junk:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for Junk
  DELTA_MINUS_VAR: energy_junk_minus
  DELTA_PLUS_VAR: energy_junk_plus
  FIELDNAM: Junk Energy

energy_ne_mg_si:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for Ne+Mg+Si
  DELTA_MINUS_VAR: energy_ne_mg_si_minus
  DELTA_PLUS_VAR: energy_ne_mg_si_plus
  FIELDNAM: Ne+Mg+Si Energy

energy_o:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for O
  DELTA_MINUS_VAR: energy_o_minus
  DELTA_PLUS_VAR: energy_o_plus
  FIELDNAM: O Energy

energy_uh:
  <<: *energy_default
  CATDESC: Geometric mean energy per nucleon for UH
  DELTA_MINUS_VAR: energy_uh_minus
  DELTA_PLUS_VAR: energy_uh_plus
  FIELDNAM: UH Energy

# ------------------------------- Label vars --------------------------------
epoch_delta_minus_label:
  CATDESC: Time from acquisition start to acquisition center
  FIELDNAM: Epoch delta minus
  FORMAT: A18
  VAR_TYPE: metadata

epoch_delta_plus_label:
  CATDESC: Time from acquisition center to acquisition end
  FIELDNAM: Epoch delta plus
  FORMAT: A18
  VAR_TYPE: metadata

# ------------------------------- Labels ------------------------------------
energy_cno_label:
  CATDESC: Energy-channel labels for CNO differential intensity
  FIELDNAM: CNO Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_fe_label:
  CATDESC: Energy-channel labels for Fe differential intensity
  FIELDNAM: Fe Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_h_label:
  CATDESC: Energy-channel labels for H differential intensity
  FIELDNAM: H Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_he3he4_label:
  CATDESC: Energy-channel labels for He3+He4 differential intensity
  FIELDNAM: He3+He4 Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_c_label:
  CATDESC: Energy-channel labels for C differential intensity
  FIELDNAM: C Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_he3_label:
  CATDESC: Energy-channel labels for He3 differential intensity
  FIELDNAM: He3 Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_he4_label:
  CATDESC: Energy-channel labels for He4 differential intensity
  FIELDNAM: He4 Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_junk_label:
  CATDESC: Energy-channel labels for Junk differential intensity
  FIELDNAM: Junk Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_ne_mg_si_label:
  CATDESC: Energy-channel labels for Ne+Mg+Si differential intensity
  FIELDNAM: Ne+Mg+Si Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_o_label:
  CATDESC: Energy-channel labels for O differential intensity
  FIELDNAM: O Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

energy_uh_label:
  CATDESC: Energy-channel labels for UH differential intensity
  FIELDNAM: UH Energy Channel Labels
  FORMAT: A32
  VAR_TYPE: metadata

# --------------------------- Dataset variable attrs ------------------------
# The following are set in multiple data products
data_quality:
  CATDESC: Indicates whether data quality is suspect (1).
  DEPEND_0: epoch
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: time_series
  FIELDNAM: Data Quality
  FILLVAL: *uint8_fillval
  FORMAT: '%d'
  LABLAXIS: Data Quality
  SCALETYP: linear
  UNITS: ' '
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: data

# ----- hi-omni Attributes -----
# Species plus and minus attrs:
energy_c_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for C
  DEPEND_1: energy_c
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: C Energy Delta Minus

energy_c_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for C
  DEPEND_1: energy_c
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: C Energy Delta Plus

energy_fe_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for Fe
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: Fe Energy Delta Minus

energy_fe_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for Fe
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: Fe Energy Delta Plus

energy_h_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for H
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: H Energy Delta Minus

energy_h_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for H
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: H Energy Delta Plus

energy_he3_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for He3
  DEPEND_1: energy_he3
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: He3 Energy Delta Minus

energy_he3_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for He3
  DEPEND_1: energy_he3
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: He3 Energy Delta Plus

energy_he4_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for He4
  DEPEND_1: energy_he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: He4 Energy Delta Minus

energy_he4_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for He4
  DEPEND_1: energy_he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: He4 Energy Delta Plus

energy_junk_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for Junk
  DEPEND_1: energy_junk
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: Junk Energy Delta Minus

energy_junk_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for Junk
  DEPEND_1: energy_junk
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: Junk Energy Delta Plus

energy_ne_mg_si_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for Ne+Mg+Si
  DEPEND_1: energy_ne_mg_si
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: Ne+Mg+Si Energy Delta Minus

energy_ne_mg_si_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for Ne+Mg+Si
  DEPEND_1: energy_ne_mg_si
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: Ne+Mg+Si Energy Delta Plus

energy_o_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for O
  DEPEND_1: energy_o
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: O Energy Delta Minus

energy_o_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for O
  DEPEND_1: energy_o
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: O Energy Delta Plus

energy_uh_minus:
  <<: *energy_default
  CATDESC: Lower energy half-width for UH
  DEPEND_1: energy_uh
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: UH Energy Delta Minus

energy_uh_plus:
  <<: *energy_default
  CATDESC: Upper energy half-width for UH
  DEPEND_1: energy_uh
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: UH Energy Delta Plus

# Uncertainty attrs:
unc_c:
  CATDESC: Uncertainty in differential intensity for C at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_c
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - C
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_c_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_fe:
  CATDESC: Uncertainty in differential intensity for Fe at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_fe
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - Fe
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_fe_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_h:
  CATDESC: Uncertainty in differential intensity for H at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_h
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - H
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_h_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_he3:
  CATDESC: Uncertainty in differential intensity for He3 at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_he3
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - He3
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he3_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_he4:
  CATDESC: Uncertainty in differential intensity for He4 at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_he4
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - He4
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he4_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_junk:
  CATDESC: Uncertainty in differential intensity for Junk at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_junk
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - Junk
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_junk_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_ne_mg_si:
  CATDESC: Uncertainty in differential intensity for Ne+Mg+Si at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_ne_mg_si
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - Ne+Mg+Si
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_ne_mg_si_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_o:
  CATDESC: Uncertainty in differential intensity for O at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_o
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - O
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_o_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_uh:
  CATDESC: Uncertainty in differential intensity for UH at root-2-spaced energy-per-nucleon channels
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_uh
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainty - UH
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_uh_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data
c:
  CATDESC: Differential intensity for C at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_c
  DELTA_PLUS_VAR: unc_c
  DEPEND_0: epoch
  DEPEND_1: energy_c
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - C
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_c_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

fe:
  CATDESC: Differential intensity for Fe at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_fe
  DELTA_PLUS_VAR: unc_fe
  DEPEND_0: epoch
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - Fe
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_fe_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

h:
  CATDESC: Differential intensity for H at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_h
  DELTA_PLUS_VAR: unc_h
  DEPEND_0: epoch
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - H
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_h_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

he3:
  CATDESC: Differential intensity for He3 at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_he3
  DELTA_PLUS_VAR: unc_he3
  DEPEND_0: epoch
  DEPEND_1: energy_he3
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - He3
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he3_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

he4:
  CATDESC: Differential intensity for He4 at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_he4
  DELTA_PLUS_VAR: unc_he4
  DEPEND_0: epoch
  DEPEND_1: energy_he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - He4
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he4_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

junk:
  CATDESC: Differential intensity for Junk at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_junk
  DELTA_PLUS_VAR: unc_junk
  DEPEND_0: epoch
  DEPEND_1: energy_junk
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - Junk
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_junk_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

ne_mg_si:
  CATDESC: Differential intensity for Ne+Mg+Si at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_ne_mg_si
  DELTA_PLUS_VAR: unc_ne_mg_si
  DEPEND_0: epoch
  DEPEND_1: energy_ne_mg_si
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - Ne+Mg+Si
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_ne_mg_si_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

o:
  CATDESC: Differential intensity for O at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_o
  DELTA_PLUS_VAR: unc_o
  DEPEND_0: epoch
  DEPEND_1: energy_o
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - O
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_o_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

uh:
  CATDESC: Differential intensity for UH at root-2-spaced energy-per-nucleon channels
  DELTA_MINUS_VAR: unc_uh
  DELTA_PLUS_VAR: unc_uh
  DEPEND_0: epoch
  DEPEND_1: energy_uh
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Differential Intensity - UH
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_uh_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data
