int_fillval: &int_fillval -9223372036854775808
max_uint32: &max_uint32 4294967295
max_uint32_min_one: &max_uint32_min_one 4294967294
max_uint16: &max_uint16 65535
min_epoch: &min_epoch -315575942816000000
max_epoch: &max_epoch 3155630469184000000

default_attrs: &default_attrs
  # TODO: Remove unneeded attributes once SAMMI is fixed
  RESOLUTION: ' '
  DISPLAY_TYPE: no_plot
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  UNITS: ' '
  FILLVAL: *int_fillval
  VALIDMIN: *min_epoch

support_data_defaults: &support_data_defaults
  <<: *default_attrs
  DEPEND_0: epoch
  VALIDMIN: 0
  VALIDMAX: 1
  DISPLAY_TYPE: time_series
  VAR_TYPE: support_data
  FORMAT: I10
  RESOLUTION: ISO8601

time_data_defaults: &time_data_defaults
  <<: *support_data_defaults
  FILLVAL: *int_fillval
  FORMAT: F16.6
  UNITS: seconds
  VALIDMAX: 4294967295.0
  VALIDMIN: 0.0

flag_data_defaults: &flag_data_defaults
  <<: *support_data_defaults
  FILLVAL: -128
  FORMAT: I2
  LABLAXIS: Flag

bins_attrs:
  <<:  *default_attrs
  VALIDMIN: 0
  VALIDMAX: 3599
  CATDESC: Histogram bin number
  FIELDNAM: Bin number
  FORMAT: I5
  VAR_TYPE: support_data
  LABLAXIS: Counts
  FILLVAL: -32768
  MONOTON: INCREASE
  SCALETYP: linear

flag_dim:
  <<: *default_attrs
  FILLVAL: -1
  CATDESC: Flags for histogram information
  FIELDNAM: Flags for histogram information
  UNITS: ' '
  FORMAT: I2
  LABLAXIS: Flags
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: support_data

within_the_second: # Used to be per_second_attrs
  <<:  *default_attrs
  VALIDMIN: 0
  VALIDMAX: 50000
  CATDESC: Direct events recorded in individual seconds # TBD any ideas how to define it
  FIELDNAM: Direct events within a second
  FORMAT: I10
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  LABLAXIS: Direct Events

direct_event_components_attrs:
  <<:  *default_attrs
  VALIDMIN: 0
  VALIDMAX: 3
  CATDESC: Components of a direct event (seconds, subseconds, impulse_length, multi_event)
  FIELDNAM: Direct event components
  FORMAT: I2
  VAR_TYPE: support_data
  LABLAXIS: Components
  FILLVAL: 255

direct_events:
  <<:  *default_attrs
  DEPEND_O: epoch
  DEPEND_1: within_the_second
  DEPEND_2: direct_event_components
  VALIDMIN: 0
  VALIDMAX: *max_uint32
  CATDESC: Direct events grouped by epoch seconds
  FIELDNAM: Direct events
  FORMAT: I10
  VAR_TYPE: data
  LABLAXIS: Counts
  FILLVAL: *max_uint32_min_one

histogram:
  <<:  *default_attrs
  VALIDMIN: 0
  VALIDMAX: 255
  CATDESC: Histogram of photon counts in scanning-circle bins
  DEPEND_0: epoch
  DEPEND_1: bins
  FIELDNAM: Histogram of photon counts
  FORMAT: I4
  DISPLAY_TYPE: time_series
  LABLAXIS: Counts
  FILL_VAL: *max_uint16
  UNITS: counts
  VAR_TYPE: data

pkts_file_name:
  <<: *support_data_defaults
  CATDESC: Name of input file with CCSDS packets data
  DISPLAY_TYPE: no_plot
  FIELDNAM: Packets-data input filename
  FILLVAL: # TBD: what is fillval for strings?
  FORMAT: S256 # TBC
  LABLAXIS: File name
  VALIDMAX: # TBD: what is validmax for a string?
  VALIDMIN: # TBD: what is validmin for a string?
  VAR_TYPE: metadata

first_spin_id:
  <<: *support_data_defaults
  CATDESC: The ordinal number of the first spin during histogram accumulation
  FIELDNAM: Number of the first spin in histogram
  FILLVAL: *max_uint32
  FORMAT: I11
  LABLAXIS: Spin number
  VALIDMAX: *max_uint32_min_one

last_spin_id:
  <<: *support_data_defaults
  CATDESC: The ordinal number of the last spin during histogram accumulation
  FIELDNAM: Number of the last spin in histogram
  FILLVAL: *max_uint32
  FORMAT: I11
  LABLAXIS: Spin number
  VALIDMAX: *max_uint32_min_one

imap_start_time:
  <<: *time_data_defaults
  CATDESC: Histogram start time, IMAP-clock seconds
  FIELDNAM: Histogram start time, IMAP-clock seconds
  LABLAXIS: Start time

imap_time_offset:
  <<: *time_data_defaults
  CATDESC: Accumulation time in seconds for GLOWS histogram
  FIELDNAM: Histogram accumulation time
  LABLAXIS: Duration
  VALIDMAX: 4000.0

glows_start_time:
  <<: *time_data_defaults
  CATDESC: Histogram start time, GLOWS-clock seconds
  FIELDNAM: Histogram start time, GLOWS-clock seconds
  LABLAXIS: Start time

glows_time_offset:
  <<: *time_data_defaults
  CATDESC: Accumulation time in seconds for GLOWS histogram
  FIELDNAM: Histogram accumulation time
  LABLAXIS: Duration
  VALIDMAX: 4000.0 # 15.38 s per spin x 256 spins = 3937.3 s, then rounded up

is_generated_on_ground:
  <<: *flag_data_defaults
  CATDESC: Flag indicating where histogram data was generated (1 - on the ground, 0 - onboard)
  FIELDNAM: Histogram-creation-site flag
  FILLVAL: -128

number_of_spins_per_block:
  <<: *support_data_defaults
  CATDESC: Number of spins per block during accumulation of histogram
  FIELDNAM: Number of spins per block
  FILLVAL: 65535
  FORMAT: I4
  LABLAXIS: Num of spins
  VALIDMAX: 256
  VALIDMIN: 1

unique_block_identifier:
  <<: *support_data_defaults
  CATDESC: YYYY-MM-DDThh:mm:ss based on IMAP UTC time
  FIELDNAM: YYYY-MM-DDThh:mm:ss based on IMAP UTC time

number_of_bins_per_histogram:
  <<: *support_data_defaults
  CATDESC: Number of histogram bins
  FIELDNAM: Number of histogram bins
  FILLVAL: *max_uint16
  FORMAT: I5
  LABLAXIS: Num of bins
  VALIDMAX: 3600
  VALIDMIN: 225

ecliptic_dim:
  <<: *default_attrs
  # TODO: Update validmin and validmax
  VALIDMIN: *int_fillval
  VALIDMAX: *max_uint32
  CATDESC: Cartesian Ecliptic X, Y, Z coordinates for the spacecraft in KM
  FIELDNAM: Cartesian Ecliptic X, Y, Z coordinates
  LABLAXIS: Ecliptic Coordinates
  UNITS: km
  FILLVAL: *int_fillval
  VAR_TYPE: support_data

number_of_events:
  <<: *support_data_defaults
  CATDESC: Total number of events/counts in the histogram
  FIELDNAM: Total number of counts in histogram
  FILLVAL: *int_fillval
  FORMAT: I11
  LABLAXIS: Num of counts
  VALIDMAX: *max_uint32

filter_temperature_average:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged filter temperature
  FIELDNAM: Average filter temperature
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Avgd Temperature
  VALIDMAX: 255

filter_temperature_variance:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged variance of filter temperature
  FIELDNAM: Variance of filter temperature
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Variance
  VALIDMAX: *max_uint16

hv_voltage_average:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged CEM voltage
  FIELDNAM: averaged CEM voltage
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Avg voltage
  VALIDMAX: *max_uint16

hv_voltage_variance:
  <<: *support_data_defaults
  CATDESC: variance of  HV voltage on the CEM, uint encoded
  FIELDNAM: HV voltage variance
  FILLVAL: *int_fillval
  LABLAXIS: Variance
  VALIDMAX: *max_uint32

spin_period_average:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged spin period
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: average spin period
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Spin period
  UNITS: ' '
  VALIDMAX: 50000 # TBC 15.38 s where 20.9712 s = 65535, rounded up
  VALIDMIN: 45000 # TBC 14.63 s where 20.9712 s = 65535, rounded down
  VAR_TYPE: support_data

spin_period_variance:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged variance of spin period
  FIELDNAM: variance of spin period
  FILLVAL: *int_fillval
  FORMAT: I10
  LABLAXIS: Variance
  VALIDMAX: *max_uint32

# TODO review these
spin_period_ground_average:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged spin period on ground
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: ground average spin period
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Spin period
  UNITS: ' '
  VALIDMAX: 50000 # TBC 15.38 s where 20.9712 s = 65535, rounded up
  VALIDMIN: 45000 # TBC 14.63 s where 20.9712 s = 65535, rounded down
  VAR_TYPE: support_data

spin_period_ground_variance:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged variance of spin period on ground
  FIELDNAM: ground variance of spin period
  FILLVAL: *int_fillval
  FORMAT: I10
  LABLAXIS: Variance
  VALIDMAX: *max_uint32

pulse_length_average:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged pulse length
  FIELDNAM: Averaged pulse length
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Avg pulse len
  VALIDMAX: 255

pulse_length_variance:
  <<: *support_data_defaults
  CATDESC: spin-block-averaged variance of pulse length
  FIELDNAM: Variance of pulse length
  FILLVAL: *max_uint32
  FORMAT: I10
  LABLAXIS: Variance
  VALIDMAX: *max_uint16

position_angle_offset_average:
  <<: *support_data_defaults
  CATDESC: spin-block averaged position angle offset
  FIELDNAM: Averaged position angle offset
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Avg pos angle

position_angle_offset_variance:
  <<: *support_data_defaults
  CATDESC: spin-block averaged variance of position angle offset
  FIELDNAM: Variance of position angle offset
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Variance

spin_axis_orientation_variance:
  <<: *support_data_defaults
  CATDESC: spin-block averaged variance of spin axis orientation
  FIELDNAM: Variance of spin axis orientation
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Variance

spin_axis_orientation_average:
  <<: *support_data_defaults
  CATDESC: spin-block averaged spin axis orientation
  FIELDNAM: Averaged spin axis orientation
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Avg spin axis orientation

spacecraft_location_average:
  <<: *support_data_defaults
  CATDESC: spin-block averaged spacecraft location
  FIELDNAM: Averaged spacecraft location
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Avg spacecraft location

spacecraft_location_variance:
  <<: *support_data_defaults
  CATDESC: spin-block averaged variance of spacecraft location
  FIELDNAM: Variance of spacecraft location
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Variance

spacecraft_velocity_average:
  <<: *support_data_defaults
  CATDESC: spin-block averaged spacecraft velocity
  FIELDNAM: Averaged spacecraft velocity
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Avg spacecraft velocity

spacecraft_velocity_variance:
  <<: *support_data_defaults
  CATDESC: spin-block averaged variance of spacecraft velocity
  FIELDNAM: Variance of spacecraft velocity
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Variance

# End of not-in--dicts in generate_de_dataset

# support_data
seq_count_in_pkts_file:
  <<: *support_data_defaults
# TBD: problem with several values associated with one epoch value
  CATDESC: Ordinal number of a packet in a sequence of multiple CCSDS packets
  FIELDNAM: Packet sequence counter
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Counter
  VALIDMAX: 65534 # uint16_max - 1, because it must be less than VALIDMAX for number_of_de_packets

number_of_de_packets:
  <<: *support_data_defaults
  CATDESC: Number of packets for a given portion (second) of direct-event data
  FIELDNAM: Number of DE packets
  FILLVAL: *max_uint32
  FORMAT: I5
  LABLAXIS: Num of packets
  VALIDMAX: *max_uint16
# End of support data

# data_every_second in glows_l1a.py
imap_time_last_pps:
  <<: *time_data_defaults
  CATDESC: IMAP-clock time for last PPS
  FIELDNAM: IMAP-clock time for last PPS
  LABLAXIS: IMAP seconds
  VALIDMAX: *max_uint32_min_one

glows_time_last_pps:
  <<: *time_data_defaults
  CATDESC: GLOWS-clock time for last PPS
  FIELDNAM: GLOWS-clock time for last PPS
  DISPLAY_TYPE: no_plot
  LABLAXIS: GLOWS seconds
  VALIDMAX: *max_uint32_min_one

imap_time_next_pps:
  <<: *time_data_defaults
  CATDESC: IMAP-clock time for next PPS
  FIELDNAM: IMAP-clock time for next PPS
  FILLVAL: *max_uint32
  LABLAXIS: IMAP seconds
  VALIDMAX: *max_uint32_min_one

catbed_heater_active:
  <<: *flag_data_defaults
  CATDESC: Catbed-heater activity flag (1 - active, 0 - not active)
  FIELDNAM: Catbed-heater activity flag

spin_period_valid:
  <<: *flag_data_defaults
  CATDESC: Spin-period-validity flag (1 - valid, 0 - invalid)
  FIELDNAM: Spin-period-validity flag

spin_phase_at_next_pps_valid:
  <<: *flag_data_defaults
  CATDESC: Spin-phase-at-next-PPS validity flag (1 - valid, 0 - invalid)
  FIELDNAM: Spin-phase-at-next-PPS validity flag

spin_period_source:
  <<: *flag_data_defaults
  CATDESC: Spin-period-source flag (0 - from ITF, 1 - estimated by GLOWS AppSW)
  FIELDNAM: Spin-period-source flag

spin_period:
  <<: *support_data_defaults
  CATDESC: spin period value
  FIELDNAM: spin period value
  FILLVAL: *max_uint16
  FORMAT: I6
  LABLAXIS: Spin period
  VALIDMAX: 50000 # TBC 15.38 s where 20.9712 s = 65535, rounded up
  VALIDMIN: 45000 # TBC 14.63 s where 20.9712 s = 65535, rounded down

# TODO: Review this
imap_spin_angle_bin_cntr:
  <<: *support_data_defaults
  CATDESC: IMAP spin angle for bin center
  FIELDNAM: IMAP spin angle for bin center
  FILLVAL: *max_uint32
  FORMAT: I11
  LABLAXIS: IMAP angle

spin_phase_at_next_pps:
  <<: *support_data_defaults
  CATDESC: next spin phase value
  FIELDNAM: next spin phase value
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Spin phase
  VALIDMAX: *max_uint16

number_of_completed_spins:
  <<: *support_data_defaults
  CATDESC: Number of completed spins
  FIELDNAM: Number of completed spins
  FILLVAL: *max_uint32
  FORMAT: I11
  LABLAXIS: Num of spins
  VALIDMAX: *max_uint32_min_one

filter_temperature:
  <<: *support_data_defaults
  CATDESC: filter temperature
  FIELDNAM: Filter temperature
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Temperature
  VALIDMAX: *max_uint16
  DISPLAY_TYPE: time_series

hv_voltage:
  <<: *support_data_defaults
  CATDESC: CEM voltage
  FIELDNAM: CEM voltage
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Voltage
  VALIDMAX: *max_uint16

glows_time_on_pps_valid:
  <<: *flag_data_defaults
  CATDESC: GLOWS-time-on-PPS-arrival validity flag (1 - valid, 0 - not valid)
  FIELDNAM: GLOWS time validity flag

time_status_valid:
  <<: *flag_data_defaults
  CATDESC: Time-status-data-structure-validity flag (1 - valid, 0 - invalid)
  FIELDNAM: Time-status-structure-validity flag

housekeeping_valid:
  <<: *flag_data_defaults
  CATDESC: GLOWS housekeeping validity flag (1 - valid, 0 - invalid)
  FIELDNAM: Housekeeping validity flag

is_pps_autogenerated:
  <<: *flag_data_defaults
  CATDESC: Flag indicating whether PPS is autogenerated (1 - autogenerated, 0 - external)
  FIELDNAM: Autogenerated-PPS flag

hv_test_in_progress:
  <<: *flag_data_defaults
  CATDESC: HV-test-in-progress flag (1 - test is on, 0 - test is off)
  FIELDNAM: HV-test-in-progress flag

pulse_test_in_progress:
  <<: *flag_data_defaults
  CATDESC: Pulse-test-in-progress flag (1 - test is on, 0 - test is off)
  FIELDNAM: Pulse-test-in-progress flag

memory_error_detected:
  <<: *flag_data_defaults
  CATDESC: Memory-error flag (1 - error detected, 0 - no error)
  FIELDNAM: Memory-error flag
# End of data_every_second

direct_event_glows_times:
  <<: *time_data_defaults
  DEPEND_1: within_the_second
  CATDESC: IMAP-clock time for direct events
  FIELDNAM: IMAP-clock time for direct_events
  LABLAXIS: Seconds
  FILLVAL: *max_uint32
  VALIDMAX: *max_uint32_min_one

# TODO: review
direct_event_pulse_lengths:
  <<: *support_data_defaults
  DEPEND_1: within_the_second
  VAR_TYPE: data
  CATDESC: Pulse lengths for direct events
  FIELDNAM: Pulse lengths for direct events
  LABLAXIS: Pulse lengths

missing_packets_sequence: # Used to be missing_packets_sequence
  <<: *support_data_defaults
  CATDESC: Missing packet sequence numbers # Make it a string
  FIELDNAM: Missing packet sequences
  FILLVAL: *int_fillval
  FORMAT: I10
  LABLAXIS: Metadata
  VALIDMAX: 1000000000
  VAR_TYPE: metadata

flight_software_version:
  <<: *support_data_defaults
  CATDESC: GLOWS flight software version
  FIELDNAM: GLOWS flight software version
  FILLVAL: *max_uint32
  LABLAXIS: Version
  VALIDMAX: 16777215

flags_set_onboard:
  # TODO: Verify uint32 fillval and uint16 validmax
  <<: *support_data_defaults
  CATDESC: Binary mask with histogram flags set onboard
  FIELDNAM: Mask with histogram flags set onboard
  FILLVAL: *max_uint32
  FORMAT: I6
  LABLAXIS: Mask value
  VALIDMAX: *max_uint16

# TODO review this
histogram_flag_array:
  <<: *flag_data_defaults
  VALIDMIN: 0
  VALIDMAX: 1

de_flags:
  <<: *flag_data_defaults
  DEPEND_1: flag_dim
  CATDESC: Flags for direct events
  FIELDNAM: Flags for direct events
  VALIDMIN: 0
  VALIDMAX: 1

flags:
  <<: *support_data_defaults
  VALIDMIN: 0
  VALIDMAX: 1
  FORMAT: I1
  FILLVAL: 0


