instrument_base: &instrument_base
  Descriptor: IDEX>Interstellar Dust Experiment
  Instrument_type: Particles (space)
  TEXT: >
    The Interstellar Dust Experiment (IDEX) is a time-of-flight (TOF)
    dust impact ionization mass spectrometer on the IMAP mission that
    provides the elemental composition, speed, and mass distributions
    of interstellar dust and interplanetary dust particles. Each record
    contains the data from a single dust impact. See
    https://imap.princeton.edu/spacecraft/instruments/interstellar-dust-experiment-idex
    for more details.

imap_idex_l1a_sci:
  <<: *instrument_base
  Data_type: L1A_SCI-10DAYS>Level-1A Science Data
  Logical_source: imap_idex_l1a_sci-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-1A 10-Day Data.

imap_idex_l1a_msg-10days:
  <<: *instrument_base
  Data_type: L1A_MSG-10DAYS>Level-1A Event Message Data
  Logical_source: imap_idex_l1a_msg-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-1A Event Message Data.

imap_idex_l1a_catlst-10days:
  <<: *instrument_base
  Data_type: L1A_CATLST-10DAYS>Level-1A Packet Catalog Summary Data
  Logical_source: imap_idex_l1a_catlst-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-1A Packet Catalog Summary Data.

imap_idex_l1b_sci:
  <<: *instrument_base
  Data_type: L1B_SCI-10DAYS>Level-1B Science 10-Day Data
  Logical_source: imap_idex_l1b_sci-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-1B 10-Day Data.

imap_idex_l1b_msg-10days:
  <<: *instrument_base
  Data_type: L1B_MSG-10DAYS>Level-1B Event Message Data
  Logical_source: imap_idex_l1b_msg-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-1B Event Message Data.

imap_idex_l1b_catlst-10days:
  <<: *instrument_base
  Data_type: L1B_CATLST-10DAYS>Level-1B Packet Catalog Summary Data
  Logical_source: imap_idex_l1b_catlst-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-1B Packet Catalog Summary Data.

imap_idex_l2a_sci:
  <<: *instrument_base
  Data_type: L2A_SCI-10DAYS>Level-2A Science 10-Day Data
  Logical_source: imap_idex_l2a_sci-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-2A 10-Day Data

imap_idex_l2b_sci:
  <<: *instrument_base
  Data_level: 2B
  Data_type: L2B_SCI-10DAYS>Level-2B Science 10-Day Data
  Logical_source: imap_idex_l2b_sci-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-2B 10-Day Data

imap_idex_l2c_sci-rectangular:
  <<: *instrument_base
  Data_level: 2C
  Data_type: L2C_RECTANGULAR-MAP-10DAYS>Level-2C Rectangular Map 10-Day Data
  Logical_source: imap_idex_l2c_rectangular-map-10days
  Logical_source_description: IMAP Mission IDEX Instrument Level-2C Rectangular Map 10-Day Data
