# ----------------------------- Useful variables -----------------------------
real_fillval: &real_fillval -1.0e+31
max_float: &max_float 3.4028235e+38

# ------------------------------- Coordinates -------------------------------
elevation_angle:
  CATDESC: Elevation Angle
  FIELDNAM: Elevation Angle
  FORMAT: I8
  LABLAXIS: Elevation Angle
  SCALETYP: linear
  UNITS: degrees
  VALIDMAX: 180.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

spin_sector:
  CATDESC: Spin Sector Index
  FIELDNAM: Spin Sector Index
  FILLVAL: -1
  FORMAT: I2
  LABLAXIS: " "
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 24
  VALIDMIN: 0
  VAR_TYPE: support_data

# spin angle:
spin_angle:
  CATDESC: Spin Angle
  DEPEND_1: spin_sector
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:ArrivalDirection,Qualifier:DirectionAngle.AzimuthAngle
  FIELDNAM: Spin Angle
  FILLVAL: *real_fillval
  FORMAT: '%f'
  LABL_PTR_1: spin_sector_label
  SCALETYP: linear
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

# ------------------------------- labels -------------------------------
elevation_angle_label:
  CATDESC: Elevation Angle
  FIELDNAM: Elevation Angle
  FORMAT: A6
  VAR_TYPE: metadata

# ------------------------------- species -------------------------------
# lo-angular attribute templates (combined versions of the previous entries)
lo-angular-attrs:
    CATDESC: "{species} {direction} species"
    DELTA_MINUS_VAR: unc_{species}
    DELTA_PLUS_VAR: unc_{species}
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DEPEND_3: elevation_angle
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "{direction} - {species}"
    FILLVAL: *real_fillval
    FORMAT: F13.4
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    LABL_PTR_3: elevation_angle_label
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: 16777216.0
    VALIDMIN: 0.0
    VAR_TYPE: data

lo-angular-unc-attrs:
    CATDESC: "{species} {direction} species uncertainty"
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DEPEND_3: elevation_angle
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Uncertainty
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "{direction} - {species}"
    FILLVAL: *real_fillval
    FORMAT: F13.4
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    LABL_PTR_3: elevation_angle_label
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: 16777216.0
    VALIDMIN: 0.0
    VAR_TYPE: support_data
