default_attrs: &default
  # Assumed values for all variable attrs unless overwritten
  DISPLAY_TYPE: time_series
  UNITS: ' '

default_uint8_attrs: &default_uint8
  <<: *default
  FILLVAL: 255
  FORMAT: I3
  VALIDMIN: 0
  VALIDMAX: 255
  dtype: uint8

default_uint16_attrs: &default_uint16
  <<: *default
  FILLVAL: 65535
  FORMAT: I5
  VALIDMIN: 0
  VALIDMAX: 65535
  dtype: uint16

default_uint32_attrs: &default_uint32
  <<: *default
  FILLVAL: 4294967295
  FORMAT: I10
  VALIDMIN: 0
  VALIDMAX: 4294967295
  dtype: uint32

default_int64_attrs: &default_int64
  <<: *default
  FILLVAL: 18446744073709551615
  FORMAT: I20
  VALIDMIN: 0
  VALIDMAX: 18446744073709551615
  dtype: int64

default_int32_attrs: &default_int32
  <<: *default
  FILLVAL: -2147483648
  FORMAT: I10
  VALIDMIN: -2147483648
  VALIDMAX: 2147483647
  dtype: int32

coord_default_attrs: &coord_default
  <<: *default
  VAR_TYPE: support_data

de_default_attrs: &de_default
  <<: *default
  VAR_TYPE: support_data
  DEPEND_1: direct_events

hist_az_60_default: &hist_az_60_default
  <<: *default_uint32
  VAR_TYPE: data
  DEPEND_0: epoch
  DEPEND_1: azimuth_60
  DEPEND_2: esa_step

hist_az_6_default: &hist_az_6_default
  <<: *default_uint32
  VAR_TYPE: data
  DEPEND_0: epoch
  DEPEND_1: azimuth_6
  DEPEND_2: esa_step

spin_default_attrs: &spin_default
  <<: *default
  VAR_TYPE: support_data
  DEPEND_1: spin


# Re-used Coordinate
epoch:
  <<: *default_int64
  CATDESC: Epoch Time
  DEPEND_0: epoch
  FIELDNAM: Epoch time
  Units: 'ns'
  VAR_TYPE: support_data
  LABLAXIS: Epoch

esa_step_label:
   CATDESC: ESA Steps
   FIELDNAM: ESA Steps
   FORMAT: A1
   VAR_TYPE: metadata

esa_step:
  <<: *coord_default
  <<: *default_uint8
  VALIDMIN: 1
  VALIDMAX: 7
  FORMAT: I1
  CATDESC: Energy Step
  DEPEND_1: esa_step
  FIELDNAM: Energy Step
  LABLAXIS: ESA
  LABL_PTR_1: esa_step_label

shcoarse:
  <<: *default_uint32
  CATDESC: Mission Elapsed Time
  DEPEND_0: epoch
  FIELDNAM: Spacecraft Time
  Units: 'ns'
  VAR_TYPE: support_data
  LABLAXIS: SHCOARSE

# Direct Events Attributes
## Coordinates
direct_events:
  <<: *de_default
  <<: *default_uint32
  CATDESC: Index of number of direct events for pointing
  FIELDNAM: direct_events
  LABLAXIS: DE

## Fields
de_time:
  <<: *de_default
  <<: *default_uint16
  VALIDMAX: 4096
  FORMAT: I4
  CATDESC: Time relative to spin start
  FIELDNAM: Direct Event Time
  UNITS: microseconds
  LABLAXIS: DE time

mode:
  <<: *de_default
  <<: *default_uint8
  VALIDMAX: 1
  FORMAT: I1
  CATDESC: Energy Stepping Mode
  FIELDNAM: ESA Mode
  LABLAXIS: ESA Mode

tof0:
  <<: *de_default
  <<: *default_uint16
  VALIDMAX: 4096
  FORMAT: I4
  CATDESC: Time of Flight
  FIELDNAM: Time of Flight 2
  LABLAXIS: ToF 0

tof1:
  <<: *de_default
  <<: *default_uint16
  VALIDMAX: 4096
  FORMAT: I4
  CATDESC: Time of Flight
  FIELDNAM: Time of Flight 1
  LABLAXIS: ToF 1

tof2:
  <<: *de_default
  <<: *default_uint16
  VALIDMAX: 4096
  FORMAT: I4
  CATDESC: Time of Flight
  FIELDNAM: Time of Flight 2
  LABLAXIS: ToF 2

tof3:
  <<: *de_default
  <<: *default_uint16
  VALIDMAX: 4096
  FORMAT: I4
  CATDESC: Time of Flight
  FIELDNAM: Time of Flight 3
  LABLAXIS: ToF 3

cksm:
  <<: *de_default
  <<: *default_uint8
  VALIDMAX: 15
  CATDESC: checksum TBD
  FIELDNAM: Checksum
  FORMAT: I2
  LABLAXIS: Checksum

pos:
  <<: *de_default
  <<: *default_uint8
  VALIDMAX: 4
  FORMAT: I1
  CATDESC: Stop position
  FIELDNAM: Stop Position
  LABLAXIS: Stop Position

coincidence_type:
  <<: *de_default
  <<: *default_uint8
  VALIDMAX: 15
  FORMAT: I2
  CATDESC: Direct Event Coincidence Type
  FIELDNAM: Coincidence Type
  LABLAXIS: Coincidence Type

de_count:
  <<: *default
  <<: *default_uint16
  VALIDMAX: 32767
  DEPEND_0: epoch
  CATDESC: Direct Event Counts
  FIELDNAM: Direct Event Count
  LABLAXIS: Direct Event Count
# Direct Events Attributes - END

# Histogram Attributes
## Coordinates
azimuth_6_label:
  CATDESC: azimuth spin bins (<num packets>, 6 degrees)
  FIELDNAM: Azimuth bins
  FORMAT: A3
  VAR_TYPE: metadata

azimuth_6:
  <<: *coord_default
  <<: *default_uint8
  VALIDMAX: 59
  CATDESC: azimuth spin bins (<num packets>, 6 degrees)
  FIELDNAM: Azimuth bins
  DEPEND_1: azimuth_6
  LABLAXIS: Az bins
  LABL_PTR_1: azimuth_6_label

azimuth_60_label:
  CATDESC: azimuth spin bins (<num packets>, 60 degrees)
  FIELDNAM: Azimuth bins
  FORMAT: A3
  VAR_TYPE: metadata

azimuth_60:
  <<: *coord_default
  <<: *default_uint8
  VALIDMAX: 5
  CATDESC: azimuth spin bins (<num packets>, 60 degrees)
  FIELDNAM: Azimuth bins
  DEPEND_1: azimuth_60
  LABLAXIS: Az bins
  LABL_PTR_1: azimuth_60_label

## Fields
start_a:
  <<: *hist_az_60_default
  CATDESC: Anode A Singles count
  FIELDNAM: Anode A Singles Count
  LABLAXIS: anode A singles counts

start_c:
  <<: *hist_az_60_default
  CATDESC: Anode C Singles count
  FIELDNAM: Anode C Singles count
  LABLAXIS: anode c singles count

stop_b0:
  <<: *hist_az_60_default
  CATDESC: Ion B0 Singles count
  FIELDNAM: Ion B0 Singles count
  LABLAXIS: ion B0 singles count

stop_b3:
  <<: *hist_az_60_default
  CATDESC: Ion B3 Singles count
  FIELDNAM: Ion B3 Singles count
  LABLAXIS: ion B3 singles count

tof0_count:
  <<: *hist_az_60_default
  CATDESC: Time of Flight 0 count
  FIELDNAM: Time of Flight 0 count
  LABLAXIS: ToF 0 count

tof1_count:
  <<: *hist_az_60_default
  CATDESC: Time of Flight 1 count
  FIELDNAM: Time of Flight 1 count
  LABLAXIS: ToF 1 count

tof2_count:
  <<: *hist_az_60_default
  CATDESC: Time of Flight 2 count
  FIELDNAM: Time of Flight 2 count
  LABLAXIS: ToF 2 count

tof3_count:
  <<: *hist_az_60_default
  CATDESC: Time of Flight 3 count
  FIELDNAM: Time of Flight 3 count
  LABLAXIS: ToF 3 count

tof0_tof1:
  <<: *hist_az_6_default
  catdesc: Triple Coincidence 0/1 count
  FIELDNAM: Triple Coincidence 0/1 count
  LABLAXIS: triple coincidence 0/1 count

tof0_tof2:
  <<: *hist_az_6_default
  CATDESC: Triple Coincidence 0/2 count
  FIELDNAM: Triple Coincidence 0/2 count
  LABLAXIS: triple coincidence 0/2 count

tof1_tof2:
  <<: *hist_az_6_default
  catdesc: Triple Coincidence 1/2 count
  FIELDNAM: Triple Coincidence 1/2 count
  LABLAXIS: triple 1/2 coincidence count

silver:
  <<: *hist_az_6_default
  CATDESC: Triple Coincidence silver count
  FIELDNAM: Triple Coincidence silver count
  LABLAXIS: triple coincidence silver count

disc_tof0:
  <<: *hist_az_60_default
  CATDESC: Discarded Time of Flight 0 count
  FIELDNAM: Discarded Time of Flight 0 count
  LABLAXIS: discarded ToF 0 count

disc_tof1:
  <<: *hist_az_60_default
  CATDESC: Discarded Time of Flight 1 count
  FIELDNAM: Discarded Time of Flight 1 count
  LABLAXIS: discarded ToF 1 count

disc_tof2:
  <<: *hist_az_60_default
  CATDESC: Discarded Time of Flight 2 count
  FIELDNAM: Discarded Time of Flight 2 count
  LABLAXIS: discarded ToF 2 count

disc_tof3:
  <<: *hist_az_60_default
  CATDESC: Discarded Time of Flight 3 count
  FIELDNAM: Discarded Time of Flight 3 count
  LABLAXIS: discarded ToF 3 count

pos0:
  <<: *hist_az_60_default
  CATDESC: Position 0 count
  FIELDNAM: Position 0 count
  LABLAXIS: position 0 count

pos1:
  <<: *hist_az_60_default
  CATDESC: Position 1 count
  FIELDNAM: Position 1 count
  LABLAXIS: position 1 count

pos2:
  <<: *hist_az_60_default
  CATDESC: Position 2 count
  FIELDNAM: Position 2 count
  LABLAXIS: position 2 count

pos3:
  <<: *hist_az_60_default
  CATDESC: Position 3 count
  FIELDNAM: Position 3 count
  LABLAXIS: position 3 count

hydrogen:
  <<: *hist_az_6_default
  CATDESC: Hydrogen count
  FIELDNAM: Hydrogen count
  LABLAXIS: hydrogen count

oxygen:
  <<: *hist_az_6_default
  CATDESC: Oxygen count
  FIELDNAM: Oxygen count
  LABLAXIS: oxygen count
# Histogram Attributes - END

# Star Sensor Attributes
## Coordinates
star_sample:
  <<: *coord_default
  <<: *default_uint16
  VALIDMAX: 719
  CATDESC: indices of star sensor samples for pointing
  FIELDNAM: Star Sensor Sample Indices in Pointing

## Fields
star_sensor:
  <<: *default_uint32
  CATDESC: Star Sensor FIFO Data
  DEPEND_1: star_sample
  VAR_TYPE: support_data
  FIELDNAM: Star Sensor FIFO Data
  LABLAXIS: star sensor FIFO data

count:
  <<: *default_uint16
  CATDESC: Number of star sensor samples in packet
  FIELDNAM: Number of star sensor samples
  DEPEND_0: epoch
  VAR_TYPE: support_data
  LABLAXIS: Number of star sensor samples
# Star Sensor Attributes - END

# Spin Attributes
## Spin Coordinates
spin:
  <<: *default_uint16
  CATDESC: Spin numbers in pointing
  FIELDNAM: Spin numbers
  DEPEND_1: spin
  VAR_TYPE: support_data
  LABLAXIS: spin numbers


## Spin Fields
num_completed:
  <<: *default_uint16
  DEPEND_0: epoch
  VAR_TYPE: support_data
  CATDESC: Number of spins completed
  FIELDNAM: Number of spins completed
  LABLAXIS: number of spins completed

acq_end:
  <<: *default_uint32
  DEPEND_0: epoch
  VAR_TYPE: support_data
  CATDESC: Acquisition End
  FIELDNAM: Acquisition End
  UNITS: ns
  LABLAXIS: acquisition end

spin_seconds:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Spin Start Seconds Time
  FIELDNAM: Spin Start Seconds Time
  UNITS: ns
  LABLAXIS: spin start seconds time

spin_subseconds:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Spin Start Sub-Seconds Time
  FIELDNAM: Spin Start Sub-Seconds Time
  LABLAXIS: spin start sub-seconds time

esa_p_dac:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Positive ESA Set Point
  FIELDNAM: Positive ESA Set Point
  LABLAXIS: Positive ESA Set Point

esa_n_dac:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Negative ESA Set Point
  FIELDNAM: Negative ESA Set Point
  LABLAXIS: Negative ESA Set Point

val_period:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Valid Spin Period
  FIELDNAM: Valid Spin Period
  LABLAXIS: valid spin period

val_spin:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Valid Spin Phase
  FIELDNAM: Valid Spin Phase
  LABLAXIS: valid spin phase

source:
  <<: *spin_default
  <<: *default_uint32
  CATDESC: Spin Period Source
  FIELDNAM: Spin Period Source
  LABLAXIS: spin period source
# Spin Attributes - END