# <=== Label Attributes ===>
# LABL_PTR_i expects VAR_TYPE of metadata with char data type.
default_attrs: &default
  # Assumed values for all variable attrs unless overwritten
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  UNITS: ' '
  VALIDMAX: 9223372036854775807
  VALIDMIN: -9223372036854775808
  VAR_TYPE: data

default_coords: &default_coords
  # Assumed values for all coordinate attrs unless overwritten
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: F2.4  # Float with 4 digits
  UNITS: counts
  VALIDMAX: 9223372036854775807
  VALIDMIN: -9223372036854775808
  VAR_TYPE: support_data

mag_support_attrs: &support_default
    <<: *default
    DICT_KEY: SPASE>Support>SupportQuantity:Other
    VAR_TYPE: support_data

mag_metadata_attrs: &metadata_default
    <<: *default
    VAR_TYPE: metadata

direction_label:
  CATDESC: magnetic field vector data
  FIELDNAM: Magnetic Field Vector
  FORMAT: A3
  VAR_TYPE: metadata

compression_label:
  CATDESC: Compression and width
  FIELDNAM: Compression and width
  FORMAT: A2
  VAR_TYPE: metadata

vector_attrs: &vectors_default
    <<: *default
    CATDESC: Magnetic field vectors with x y z varying by time
    CDF_DATA_TYPE: CDF_FLOAT
    DEPEND_1: direction
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:DSRF,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field Vector
    FILLVAL: 9223372036854775807
    FORMAT: F12.5
    LABL_PTR_1: direction_label

# Frame-specific vector attributes
vector_attrs_srf:
    <<: *vectors_default
    CATDESC: Magnetic field vectors with x y z varying by time in Spacecraft Reference Frame
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:SRF,CoordinateRepresentation:Cartesian"

vector_attrs_dsrf:
    <<: *vectors_default
    CATDESC: Magnetic field vectors with x y z varying by time in Despun Spacecraft Reference Frame
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:DSRF,CoordinateRepresentation:Cartesian"

vector_attrs_gse:
    <<: *vectors_default
    CATDESC: Magnetic field vectors with x y z varying by time in Geocentric Solar Ecliptic Reference Frame
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:GSE,CoordinateRepresentation:Cartesian"

vector_attrs_gsm:
    <<: *vectors_default
    CATDESC: Magnetic field vectors with x y z varying by time in Geocentric Solar Magnetospheric Reference Frame
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:GSM,CoordinateRepresentation:Cartesian"

vector_attrs_rtn:
    <<: *vectors_default
    CATDESC: Magnetic field vectors with r t n varying by time in Radial-Tangential-Normal Reference Frame
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:RTN,CoordinateRepresentation:Cartesian"

direction_attrs:
    <<: *default_coords
    CATDESC: Magnetic field vector
    DICT_KEY: SPASE>Support>SupportQuantity:Orientation
    DISPLAY_TYPE: time_series
    FIELDNAM: \[xyz\] magnetic field vector
    FORMAT: I3
    LABLAXIS: Magnetic field vector
    VAR_TYPE: support_data


magnitude:
  <<: *support_default
  CATDESC: Magnitude of the magnetic field vector
  CDF_DATA_TYPE: CDF_FLOAT
  DICT_KEY: SPASE>Field>FieldQuantity:Magnetic,Qualifier:Scalar
  FIELDNAM: Magnetic Field Magnitude
  FILLVAL: -1.0e+31
  FORMAT: F12.5
  LABLAXIS: "|B|"
  UNITS: nT
  VALIDMAX: 1.0e+5
  VALIDMIN: 0

range:
  <<: *support_default
  CATDESC: Sensor range setting
  CDF_DATA_TYPE: CDF_UINT1
  DICT_KEY: SPASE>Support>SupportQuantity:InstrumentMode
  FIELDNAM: Sensor Range
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: Range
  UNITS: ' '
  VALIDMAX: 3
  VALIDMIN: 0

pri_sens:
    <<: *support_default
    CATDESC: Indicates the primary sensor. 0 is MAGo, 1 is MAGi
    DICT_KEY: SPASE>Support>SupportQuantity:InstrumentMode
    FIELDNAM: Primary Sensor
    FILLVAL: 255
    FORMAT: I1
    LABLAXIS: Primary Sensor
    UNITS: ' '
    VALIDMAX: 1
    VALIDMIN: 0


qf_bitmask:
  <<: *support_default
  CATDESC: Eight-bit Data quality bitmask
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Quality Flag
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: QF
  VALIDMAX: 255
  VALIDMIN: 0

qf:
  <<: *support_default
  CATDESC: Data quality flag
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Quality Flag
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: QF
  VALIDMAX: 1
  VALIDMIN: 0
