# ----------------------------- Useful variables -----------------------------
uint8_fillval: &uint8_fillval 255
real_fillval: &real_fillval -1.0e+31

min_int: &min_int -9223372036854775808
max_int: &max_int 9223372036854775807

# --------------------------- Default attributes -----------------------------
energy_attrs: &energy_default
  CATDESC: Geometric mean energy per nucleon
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Characteristic
  FIELDNAM: Energy Table
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: linear
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

# ------------------------------- Coordinates -------------------------------
epoch:
  DELTA_MINUS_VAR: epoch_delta_minus
  DELTA_PLUS_VAR: epoch_delta_plus

epoch_delta_minus:
  CATDESC: Time from acquisition start to acquisition center
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal,Qualifier:Uncertainty
  FIELDNAM: epoch delta minus
  FILLVAL: *min_int
  FORMAT: I19
  LABLAXIS: Epoch Delta Minus
  SCALETYP: linear
  UNITS: ns
  VALIDMAX: 128000000000
  VALIDMIN: 0
  VAR_TYPE: support_data

epoch_delta_plus:
  CATDESC: Time from acquisition center to acquisition end
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal,Qualifier:Uncertainty
  FIELDNAM: epoch delta plus
  FILLVAL: *min_int
  FORMAT: I19
  LABLAXIS: Epoch Delta Plus
  SCALETYP: linear
  UNITS: ns
  VALIDMAX: 128000000000
  VALIDMIN: 0
  VAR_TYPE: support_data

elevation_angle:
  CATDESC: Elevation Angle
  FIELDNAM: Elevation Angle
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Elevation Angle
  SCALETYP: linear
  UNITS: degrees
  VALIDMAX: 180.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

spin_sector:
  CATDESC: Spin Sector Index
  FIELDNAM: Spin Sector Index
  FILLVAL: *uint8_fillval
  FORMAT: I3
  LABLAXIS: " "
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 12
  VALIDMIN: 0
  VAR_TYPE: support_data

energy_cno:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_cno_minus
  DELTA_PLUS_VAR: energy_cno_plus

energy_fe:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_fe_minus
  DELTA_PLUS_VAR: energy_fe_plus

energy_h:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_h_minus
  DELTA_PLUS_VAR: energy_h_plus

energy_he3he4:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_he3he4_minus
  DELTA_PLUS_VAR: energy_he3he4_plus

# ------------------------------- Label vars --------------------------------
event_num_label:
  CATDESC: Event Number
  FIELDNAM: Event Number
  FORMAT: A5
  VAR_TYPE: metadata

epoch_delta_minus_label:
  CATDESC: Time from acquisition start to acquisition center
  FIELDNAM: Epoch delta minus
  FORMAT: A18
  VAR_TYPE: metadata

epoch_delta_plus_label:
  CATDESC: Time from acquisition center to acquisition end
  FIELDNAM: Epoch delta plus
  FORMAT: A18
  VAR_TYPE: metadata

elevation_angle_label:
  CATDESC: Elevation Angle
  FIELDNAM: Elevation Angle
  FORMAT: A6
  VAR_TYPE: metadata

spin_sector_label:
  CATDESC: Spin Sector
  DEPEND_1: spin_sector
  FIELDNAM: Spin Sector
  FORMAT: A2
  VAR_TYPE: metadata

# ------------------------------- Labels ------------------------------------
energy_cno_label:
  CATDESC: Energy CNO
  FIELDNAM: Energy CNO
  FORMAT: A6
  VAR_TYPE: metadata

energy_fe_label:
  CATDESC: Energy Fe
  FIELDNAM: Energy Fe
  FORMAT: A6
  VAR_TYPE: metadata

energy_h_label:
  CATDESC: Energy H
  FIELDNAM: Energy H
  FORMAT: A6
  VAR_TYPE: metadata

energy_he3he4_label:
  CATDESC: Energy He3He4
  FIELDNAM: Energy He3He4
  FORMAT: A6
  VAR_TYPE: metadata

# --------------------------- Dataset variable attrs ------------------------
data_quality:
  CATDESC: Indicates whether data quality is suspect (1).
  DEPEND_0: epoch
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: time_series
  FIELDNAM: Data Quality
  FILLVAL: *uint8_fillval
  FORMAT: '%d'
  LABLAXIS: Data Quality
  SCALETYP: linear
  UNITS: ' '
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: data
  VAR_TYPE: support_data

species_dim_attrs: &species_dim_attrs
  DEPEND_0: epoch
  DEPEND_1: energy_{species}
  DEPEND_2: spin_sector
  DEPEND_3: elevation_angle
  LABL_PTR_1: energy_{species}_label
  LABL_PTR_2: spin_sector_label
  LABL_PTR_3: elevation_angle_label

# species:
cno:
  <<: *species_dim_attrs
  CATDESC: cno (x2 spacing)
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: spectrogram
  FIELDNAM: cno
  FILLVAL: *real_fillval
  FORMAT: E14.7
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

fe:
  <<: *species_dim_attrs
  CATDESC: fe (x2 spacing)
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: spectrogram
  FIELDNAM: fe
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

h:
  <<: *species_dim_attrs
  CATDESC: h (x2 spacing)
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: spectrogram
  FIELDNAM: h
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

he3he4:
  <<: *species_dim_attrs
  CATDESC: he3he4 (x2 spacing)
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: spectrogram
  FIELDNAM: he3he4
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

# uncertainties:
unc_cno:
  <<: *species_dim_attrs
  CATDESC: Uncertainties for cno (x2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Uncertainties for cno
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: data

unc_fe:
  <<: *species_dim_attrs
  CATDESC: Uncertainties for fe (x2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Uncertainties for fe
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: data

unc_h:
  <<: *species_dim_attrs
  CATDESC: Uncertainties for h (x2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Uncertainties for h
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: data

unc_he3he4:
  <<: *species_dim_attrs
  CATDESC: Uncertainties for he3he4 (x2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Uncertainties for he3he4
  FILLVAL: *real_fillval
  FORMAT: F32.1
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: data

# energy deltas:
energy_cno_minus:
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_cno
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_cno_plus:
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_cno
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_fe_minus:
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_fe_plus:
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_h_minus:
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_h_plus:
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_he3he4_minus:
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_he3he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

energy_he3he4_plus:
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_he3he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

# spin angles:
spin_angle:
  CATDESC: Spin Angle
  DEPEND_1: spin_sector
  DEPEND_2: elevation_angle
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:ArrivalDirection,Qualifier:DirectionAngle.AzimuthAngle
  FIELDNAM: Spin Angle
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: spin_sector_label
  LABL_PTR_2: elevation_angle_label
  SCALETYP: log
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data
