# TODO: add attributes for science packets

# <=== Defaults ===>
# Assumed values for all variable attrs unless overwritten
default_attrs: &default
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  SCALETYP: linear
  UNITS: ' '
  VALIDMAX: 9223372036854775807
  VALIDMIN: 0
  VAR_TYPE: data

hk_support_attrs: &hk_support_default
  <<: *default
  DISPLAY_TYPE: no_plot
  VAR_TYPE: ignore_data

hk_metadata_attrs: &metadata_default
  FORMAT: A2
  VAR_TYPE: metadata

default_uint32_attrs: &default_uint32
  <<: *default
  FILLVAL: 4294967295
  FORMAT: I10
  VALIDMAX: 4294967295
  VALIDMIN: 0
  dtype: uint32

# <=== Coordinates ===>
adc_channels:   # adc_channels is a dependency for leak_i data variable
  CATDESC: ADC Channel
  DISPLAY_TYPE: no_plot
  FIELDNAM: ADC Channel
  FILLVAL: -9223372036854775808
  FORMAT: I2
  LABLAXIS: Channel
  SCALETYP: linear
  UNITS: ' '
  VALIDMAX: 63
  VALIDMIN: 0
  VAR_TYPE: metadata

# <=== Label Attributes ===>
# LABL_PTR_i expects VAR_TYPE of metadata with char data type

adc_channels_label:
  CATDESC: Analog Digital Converter Channels
  FIELDNAM: ADC Channels
  FORMAT: A2
  VAR_TYPE: metadata


# <=== Data Variable Attributes ===>

sc_tick:
  <<: *default_uint32
  CATDESC: CCSDS secondary header - Spacecraft Tick
  FIELDNAM: Spacecraft Tick
  VAR_TYPE: support_data

fsw_version_a:
  <<: *hk_support_default
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number A
  FORMAT: I2
  LABLAXIS: FSW A
  VALIDMAX: 63

fsw_version_b:
  <<: *hk_support_default
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number B
  FORMAT: I2
  LABLAXIS: FSW B
  VALIDMAX: 63

fsw_version_c:
  <<: *hk_support_default
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number C
  FORMAT: I2
  LABLAXIS: FSW C
  VALIDMAX: 63

num_good_cmds:
  <<: *hk_support_default
  CATDESC: Number of Good Commands
  FIELDNAM: Number of Good Commands
  FORMAT: I3
  LABLAXIS: Counts
  VALIDMAX: 255

last_good_cmd:
  <<: *hk_support_default
  CATDESC: Last Good Command
  FIELDNAM: Last Good Command
  FORMAT: I3
  LABLAXIS: Last cmd
  VALIDMAX: 255

last_good_seq_num:
  <<: *hk_support_default
  CATDESC: Last Good Sequence Number
  FIELDNAM: Last Good Sequence Number
  FORMAT: I3
  LABLAXIS: Last num
  VALIDMAX: 255

num_bad_cmds:
  <<: *hk_support_default
  CATDESC: Number of Bad Commands
  FIELDNAM: Number of Bad Commands
  FORMAT: I3
  LABLAXIS: Counts
  VALIDMAX: 255

last_bad_cmd:
  <<: *hk_support_default
  CATDESC: Last Bad Command
  FIELDNAM: Last Bad Command
  FORMAT: I3
  LABLAXIS: Last cmd
  VALIDMAX: 255

last_bad_seq_num:
  <<: *hk_support_default
  CATDESC: Last Bad Sequence Number
  FIELDNAM: Last Bad Sequence Number
  FORMAT: I3
  LABLAXIS: Last num
  VALIDMAX: 255

fee_running:
  <<: *metadata_default
  CATDESC: State - FEE Running (1) or Reset (0)
  FIELDNAM: FEE Running (1) or Reset (0)
  FORMAT: A7
  LABLAXIS: State

mram_disabled:
  <<: *metadata_default
  CATDESC: State - MRAM Disabled (1) or Enabled (0)
  FIELDNAM: MRAM Disabled (1) or Enabled (0)
  FORMAT: A8
  LABLAXIS: State

enable_50khz:
  <<: *metadata_default
  CATDESC: State - 50kHz Enabled (1) or Disabled (0)
  FIELDNAM: 50kHz Enabled (1) or Disabled (0)
  FORMAT: A8
  LABLAXIS: State

enable_hvps:
  <<: *metadata_default
  CATDESC: State - HVPS Enabled (1) or Disabled (0)
  FIELDNAM: HVPS Enabled (1) or Disabled (0)
  FORMAT: A8
  LABLAXIS: State

table_status:
  <<: *metadata_default
  CATDESC: State - Table Status OK (1) or Error (0)
  FIELDNAM: Table Status OK (1) or Error (0)
  FORMAT: A5
  LABLAXIS: Status

heater_control:
  <<: *metadata_default
  CATDESC: State - Heater Control (0=None, 1=Pri, 2=Sec)
  FIELDNAM: Heater Control (0=None, 1=Pri, 2=Sec)
  FORMAT: A4
  LABLAXIS: State

adc_mode:
  <<: *metadata_default
  CATDESC: State - ADC Mode (0=quiet, 1=normal, 2=adcstim, 3=adcThreshold
  FIELDNAM: ADC Mode (0=quiet, 1=normal, 2=adcstim, 3=adcThreshold)
  FORMAT: A12
  LABLAXIS: ADC mode

mode:
  <<: *metadata_default
  CATDESC: State - Mode (0=Boot, 1=Maintenance, 2=Standby, 3=Science)
  FIELDNAM: Mode (0=Boot, 1=Maintenance, 2=Standby, 3=Science)
  FORMAT: A11
  LABLAXIS: Mode

dyn_thresh_lvl:
  <<: *hk_support_default
  CATDESC: Dynamic Threshold Level (0-3)
  FIELDNAM: Dynamic Threshold Level (0-3)
  FORMAT: I1
  LABLAXIS: Level
  VALIDMAX: 3

num_evnt_last_hk:
  <<: *hk_support_default
  CATDESC: Number of Events Since Last HK Update
  FIELDNAM: Number of Events Since Last HK Update
  FORMAT: I10
  LABLAXIS: Num events
  VALIDMAX: 4294967295

num_errors:
  <<: *hk_support_default
  CATDESC: Number of Errors
  FIELDNAM: Number of Errors
  FORMAT: I3
  LABLAXIS: Num errors
  VALIDMAX: 255

last_error_num:
  <<: *metadata_default
  CATDESC: State - Last Error Number
  FIELDNAM: Last Error Number
  FORMAT: A18
  LABLAXIS: Error num

code_checksum:
  <<: *hk_support_default
  CATDESC: Code Checksum
  FIELDNAM: Code Checksum
  FORMAT: I5
  LABLAXIS: Checksum
  VALIDMAX: 65535

spin_period_short:
  <<: *hk_support_default
  CATDESC: Spin Period Short at T=0
  FIELDNAM: Spin Period Short at T=0
  FORMAT: I5
  LABLAXIS: Spin period short
  VALIDMAX: 65535

spin_period_long:
  <<: *hk_support_default
  CATDESC: Spin Period Long at T=0
  FIELDNAM: Spin Period Long at T=0
  FORMAT: I5
  LABLAXIS: Spin period long
  VALIDMAX: 65535

leak_i:
  <<: *hk_support_default
  CATDESC: Leakage Current [I]
  DEPEND_1: adc_channels
  FIELDNAM: Leakage Current [I]
  FORMAT: I19
  LABLAXIS: Current I
  labl_ptr: adc_channels

phasic_stat:
  <<: *metadata_default
  CATDESC: State - Phasic Status
  FIELDNAM: Phasic Status
  FORMAT: A7
  LABLAXIS: Status

active_heater:
  <<: *metadata_default
  CATDESC: State - Active Heater
  FIELDNAM: Active Heater
  FORMAT: A9
  LABLAXIS: State

heater_on:
  <<: *metadata_default
  CATDESC: State - Heater On/Off
  FIELDNAM: Heater On/Off
  FORMAT: A3
  LABLAXIS: State

test_pulser_on:
  <<: *metadata_default
  CATDESC: State - Test Pulser On/Off
  FIELDNAM: Test Pulser On/Off
  FORMAT: A3
  LABLAXIS: State

dac0_enable:
  <<: *metadata_default
  CATDESC: State - DAC 0 Enable
  FIELDNAM: DAC 0 Enable
  FORMAT: A7
  LABLAXIS: State

dac1_enable:
  <<: *metadata_default
  CATDESC: State - DAC 1 Enable
  FIELDNAM: DAC 1 Enable
  FORMAT: A7
  LABLAXIS: State

preamp_l234a:
  <<: *default
  CATDESC: Preamp L234A Voltage
  FIELDNAM: Preamp L234A Voltage
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

preamp_l1a:
  <<: *default
  CATDESC: Preamp L1A Voltage
  FIELDNAM: Preamp L1A Voltage
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

preamp_l1b:
  <<: *default
  CATDESC: Preamp L1B Voltage
  FIELDNAM: Preamp L1B Voltage
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

preamp_l234b:
  <<: *default
  CATDESC: Preamp L234B Voltage
  FIELDNAM: Preamp L234B Voltage
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

temp0:
  <<: *default
  CATDESC: FEE LDO Regulator Mounted on the Board Next to the Low-dropout Regulator
  FIELDNAM: FEE LDO Regulator
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

temp1:
  <<: *default
  CATDESC: Primary Heater Mounted on the Board Next to the Primary Heater Circuit
  FIELDNAM: Primary Heater
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

temp2:
  <<: *default
  CATDESC: FEE FPGA Mounted on the Board Next to the FPGA
  FIELDNAM: FEE FPGA
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

temp3:
  <<: *default
  CATDESC: Secondary Heater
  FIELDNAM: Secondary Heater
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

analog_temp:
  <<: *default
  CATDESC: Chassis Temp Mounted on the Analog Board Close to Thermostats, Heaters, and Chassis
  FIELDNAM: Analog Temp
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

hvps_temp:
  <<: *default
  CATDESC: Board Temp Mounted Inside Faraday Cage in Middle of Board Near Connector Side
  FIELDNAM: Board Temp
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

idpu_temp:
  <<: *default
  CATDESC: LDO Temp Mounted on Top of the Low-dropout Regulator
  FIELDNAM: LDO Temp
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

lvps_temp:
  <<: *default
  CATDESC: Board Temp Mounted in the Middle of Board on Opposite Side of Hottest Component
  FIELDNAM: Board Temp
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Temperature
  UNITS: C
  VALIDMAX: 10000000000
  VALIDMIN: -25

ebox_3d4vd:
  <<: *default
  CATDESC: 3.4VD Ebox (Digital)
  FIELDNAM: 3.4VD Ebox (Digital)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

ebox_5d1vd:
  <<: *default
  CATDESC: 5.1VD Ebox (Digital)
  FIELDNAM: 5.1VD Ebox (Digital)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

ebox_p12va:
  <<: *default
  CATDESC: +12VA Ebox (Analog)
  FIELDNAM: +12VA Ebox (Analog)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

ebox_m12va:
  <<: *default
  CATDESC: -12VA Ebox (Analog)
  FIELDNAM: -12VA Ebox (Analog)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000
  VALIDMIN: -12.2

ebox_p5d7va:
  <<: *default
  CATDESC: +5.7VA Ebox (Analog)
  FIELDNAM: +5.7VA Ebox (Analog)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

ebox_m5d7va:
  <<: *default
  CATDESC: -5.7VA Ebox (Analog)
  FIELDNAM: -5.7VA Ebox (Analog)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000
  VALIDMIN: -6

ref_p5v:
  <<: *default
  CATDESC: +5V ref
  FIELDNAM: +5V ref
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

l1ab_bias:
  <<: *default
  CATDESC: L1A/B Bias
  FIELDNAM: L1A/B Bias
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

l2ab_bias:
  <<: *default
  CATDESC: L2A/B Bias
  FIELDNAM: L2A/B Bias
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

l34a_bias:
  <<: *default
  CATDESC: L3/4A Bias
  FIELDNAM: L3/4A Bias
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

l34b_bias:
  <<: *default
  CATDESC: L3/4B Bias
  FIELDNAM: L3/4B Bias
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

ebox_p2d0vd:
  <<: *default
  CATDESC: +2.0VD Ebox (Digital)
  FIELDNAM: +2.0VD Ebox (Digital)
  FILLVAL: -1.0000000E+31
  FORMAT: F9.3
  LABLAXIS: Voltage
  UNITS: V
  VALIDMAX: 10000000000

