# <=== Coordinates ===>
esa_step:
  CATDESC: Energy step id in lookup table
  FIELDNAM: Energy Step
  FILLVAL: -9223370000000000000
  FORMAT: I2
  LABLAXIS: Energy Step
  SCALE_TYP: linear
  UNITS: " "
  VALIDMAX: 23
  VALIDMIN: 0
  VAR_TYPE: support_data

spin_sector:
  CATDESC: Spin sector. 30 measurements nominally
  FIELDNAM: Spin Sector
  FILLVAL: -9223370000000000000
  FORMAT: I2
  LABLAXIS: Spin Sector
  SCALE_TYP: linear
  UNITS: " "
  VALIDMAX: 29
  VALIDMIN: 0
  VAR_TYPE: support_data

cem_id:
  CATDESC: CEM detector number
  FIELDNAM: CEM Number
  FILLVAL: -9223370000000000000
  FORMAT: I2
  LABLAXIS: CEM Number
  SCALE_TYP: linear
  UNITS: " "
  VALIDMAX: 6
  VALIDMIN: 0
  VAR_TYPE: support_data

cycle:
  CATDESC: Full cycle data takes 4 spins' data
  FIELDNAM: Quarter Cycle
  FILLVAL: -9223370000000000000
  FORMAT: I2
  LABLAXIS: Cycle
  SCALE_TYP: linear
  UNITS: " "
  VALIDMAX: 3
  VALIDMIN: 0
  VAR_TYPE: support_data

# <=== Label Attributes ===>
# LABL_PTR_i expects VAR_TYPE of metadata with char data type
esa_step_label:
  CATDESC: Energy step id in lookup table
  FIELDNAM: Energy Step ID
  FORMAT: A2
  VAR_TYPE: metadata

spin_sector_label:
  CATDESC: Spin sector. 30 measurements nominally
  FIELDNAM: Measurement
  FORMAT: A2
  VAR_TYPE: metadata

cem_id_label:
  CATDESC: Data rates of each CEM detector
  FIELDNAM: CEM Rates
  FORMAT: A1
  VAR_TYPE: metadata

cycle_label:
  CATDESC: Quarter cycle number
  FIELDNAM: Quarter Cycle
  FORMAT: A1
  VAR_TYPE: metadata

# <=== Data Variables ===>
# Default Attrs for all data variables unless overridden

default_attrs: &default
  DEPEND_0: epoch
  DEPEND_1: cycle
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I20
  LABL_PTR_1: cycle_label
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 9223372036854769664
  VALIDMIN: 0
  VAR_TYPE: support_data

science_data:
  CATDESC: Electron count rates organized by voltage step and spin sector and CEM
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_sector
  DEPEND_3: cem_id
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Counts rate by volt step and spin sector and CEM
  FILLVAL: -9223372036854775808
  FORMAT: E14.7
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_sector_label
  LABL_PTR_3: cem_id_label
  UNITS: counts/sec
  VALIDMAX: 0.000015514
  VALIDMIN: 0
  VAR_NOTES: >
    Metadata field acq_duration is 17 uint. Max value of uint17 is 131071.
    Dividing max counts by acq_duration gave validmax
  VAR_TYPE: data

counts_stat_uncert:
  CATDESC: Counts statistical uncertainty
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_sector
  DEPEND_3: cem_id
  DICT_KEY: SPASE>Particle>ParticleType:Electron,ParticleQuantity:Counts,Qualifier:Uncertainty
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Counts Stats Uncertainty
  FILLVAL: -1.0000000E+31
  FORMAT: E19.5
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_sector_label
  LABL_PTR_3: cem_id_label
  SCALETYP: linear
  UNITS: counts
  VALIDMAX: 1.7976931348623157e+308 # TODO: find actual value
  VALIDMIN: 0.0
  VAR_TYPE: data

acquisition_time:
  CATDESC: Acquisition time organized by voltage step and spin sector
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_sector
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Acquisition time by volt step and spin sector
  FILLVAL: -9223372036854775808
  FORMAT: I10
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_sector_label
  UNITS: sec
  VALIDMAX: 3155716869184000000  # 2100-01-01T00:00:00 mission end
  VALIDMIN: 315576066184000000   # 2010-01-01T00:00:00 mission start (APL 0 epoch)
  VAR_NOTES: >
    This stores the acquisition times of each measurement. This time is
    calculated by combining ACQ_START_COARSE, ACQ_START_FINE,
    acquisition duration and settle duration. It is time of each energy
    step and each science measurement.
  VAR_TYPE: support_data

acq_duration:
  CATDESC: Acquisition duration
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_sector
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Acquisition Duration
  FILLVAL: -9223372036854775808
  FORMAT: I10
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_sector_label
  UNITS: microseconds
  VALIDMAX: 4290000000
  VALIDMIN: 0
  VAR_TYPE: support_data

esa_energy:
  CATDESC: ESA electron energy
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_sector
  DISPLAY_TYPE: time_series
  FIELDNAM: ESA Energies
  FILLVAL: -9223372036854775808
  FORMAT: E14.7
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_sector_label
  UNITS: eV
  VALIDMAX: 65535
  VALIDMIN: 0.000015514
  VAR_TYPE: support_data

shcoarse:
  <<: *default
  CATDESC: Mission elapsed time
  FIELDNAM: SHCOARSE

acq_start_coarse:
  <<: *default
  CATDESC: Acquisition start time coarse in seconds
  FIELDNAM: Acquisition Time Coarse

acq_start_fine:
  <<: *default
  CATDESC: Acquisition start time fine in microseconds
  FIELDNAM: Acquisition Time Fine
  FORMAT: I10
  VALIDMAX: 4290000000

cem_nominal_only:
  <<: *default
  CATDESC: CEM Nominal status bit. '1' -- nominal, '0' -- not nominal
  FIELDNAM: CEM Nominal Status
  FORMAT: I1
  VALIDMAX: 1

spin_period_validity:
  <<: *default
  CATDESC: Spin period valid bit. '1' -- valid, '0' -- invalid
  FIELDNAM: Spin Period Validity
  FORMAT: I1
  VALIDMAX: 1

spin_phase_validity:
  <<: *default
  CATDESC: Spin phase valid bit. '1' -- valid, '0' -- invalid
  FIELDNAM: Spin Phase Validity
  FORMAT: I1
  VALIDMAX: 1

spin_period_source:
  <<: *default
  CATDESC: >
    Spin period source bit. '1' -- sun sensor (safing), '0' -- star tracker
    (nominal)
  FIELDNAM: Spin Period Source
  FORMAT: I1
  VALIDMAX: 1

settle_duration:
  <<: *default
  CATDESC: HVPS settling duration
  FIELDNAM: HVPS Setting Duration
  FORMAT: I5
  VALIDMAX: 65535

spin_phase:
  <<: *default
  CATDESC: Spin phase
  FIELDNAM: Spin Phase
  FILLVAL: -9223372036854775808
  FORMAT: E14.7
  VALIDMAX: 65535

spin_period:
  <<: *default
  CATDESC: Spin period
  FIELDNAM: Spin Period
  FILLVAL: -9223372036854775808
  FORMAT: E14.7
  VALIDMAX: 65535

repoint_warning:
  <<: *default
  CATDESC: >
    Thruster fired during this quarter cycle. '1' -- yes, warning received,
    '0' -- no, warning not received
  FIELDNAM: Repointing Warning
  FORMAT: I1
  VALIDMAX: 1

high_count:
  <<: *default
  CATDESC: >
    High CEM count observed for at least one CEM during this quarter cycle.
    '1' -- yes, high count occurred, '0' -- no, no high count occurred
  FIELDNAM: High Count
  FORMAT: I1
  VALIDMAX: 1

stim_enabled:
  <<: *default
  CATDESC: Stim state. '1' -- enabled, '0' -- disabled
  FIELDNAM: Stim State
  FORMAT: I1
  VALIDMAX: 1

quarter_cycle:
  <<: *default
  CATDESC: Quarter cycle number
  FIELDNAM: Quarter Cycle Number
  FORMAT: I3
  VALIDMAX: 255

esa_table_num:
  <<: *default

  CATDESC: ESA table identifier
  FIELDNAM: ESA table Identifier
  FORMAT: I3
  VALIDMAX: 255

esa_acq_cfg:
  <<: *default
  CATDESC: ESA acquisition configuration
  FIELDNAM: ESA Acquisition Configuration
  FORMAT: I3
  VALIDMAX: 255

threshold_dac:
  <<: *default
  CATDESC: Threshold DAC value
  FIELDNAM: Threshold DAC Value
  FILLVAL: -9223372036854775808
  FORMAT: E14.7
  VALIDMAX: 65535

stim_cfg_reg:
  <<: *default
  CATDESC: >
    Stim pulse configuration register. Bits 0-3, period, 4-7, duration, 8-9
    mode
  FIELDNAM: Stim Pulse Configuration
  FORMAT: I5
  VALIDMAX: 65535

cksum:
  <<: *default
  CATDESC: Checksum
  FIELDNAM: Checksum
  FORMAT: I5
  VALIDMAX: 65535

data_quality:
  CATDESC: >
    In-flight calibration quality flags. Bit 2 (LAST_CAL_INTERVAL): set if any
    acquisition time in this cycle was extrapolated using the last two entries
    in the calibration table.
  DEPEND_0: epoch
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: time_series
  FIELDNAM: SWE data quality flags
  FILLVAL: 255
  FORMAT: I3
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 255
  VALIDMIN: 0
  VAR_NOTES: >
    There is 1 flag currently in use. Stored as a bitwise flag. Bit 2
    (LAST_CAL_INTERVAL, value 4): counter values were extrapolated using the last two
    calibration table entries. All other bits are reserved.
  VAR_TYPE: support_data

# <=== HK Variables ===>
# L1B HK data attrs for data with string values
l1b_hk_string_attrs:
  CATDESC: Housekeeping derived data
  DEPEND_0: epoch
  FIELDNAM: Housekeeing Human Readable State
  FORMAT: A80
  VAR_TYPE: metadata

l1b_hk_attrs:
  CATDESC: SWE HK data
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: SWE Housekeeping Data
  FILLVAL: -9223372036854775808
  FORMAT: I19
  LABLAXIS: Values
  UNITS: ' '
  VALIDMAX: 9223372036854769664
  VALIDMIN: 0
  VAR_TYPE: support_data
