int_fillval: &int_fillval -9223372036854775808
int_maxval: &int_maxval 9223372036854775807
double_fillval: &double_fillval -1.0E31

# Base attributes for charge and mass variables
base_charge: &base_charge
  CATDESC: " "
  DEPEND_0: epoch
  DEPEND_1: impact_charge
  DEPEND_2: spin_phase
  DISPLAY_TYPE: spectrogram
  FIELDNAM: " "
  FILLVAL: *int_fillval
  FORMAT: E10.3
  LABL_PTR_1: charge_labels
  LABL_PTR_2: spin_phase_labels
  VALIDMAX: *int_maxval
  VALIDMIN: -1
  VAR_TYPE: data

base_mass: &base_mass
  CATDESC: " "
  DEPEND_0: epoch
  DEPEND_1: mass
  DEPEND_2: spin_phase
  DISPLAY_TYPE: spectrogram
  FIELDNAM: " "
  FILLVAL: *int_fillval
  FORMAT: E10.3
  LABL_PTR_1: mass_labels
  LABL_PTR_2: spin_phase_labels
  VALIDMAX: *int_maxval
  VALIDMIN: 0.0
  VAR_TYPE: data

base_charge_map: &base_charge_map
  <<: *base_charge
  DEPEND_2: rectangular_lon_pixel
  DEPEND_3: rectangular_lat_pixel
  LABL_PTR_2: rectangular_lon_pixel_label
  LABL_PTR_3: rectangular_lat_pixel_label

base_mass_map: &base_mass_map
  <<: *base_mass
  DEPEND_2: rectangular_lon_pixel
  DEPEND_3: rectangular_lat_pixel
  LABL_PTR_2: rectangular_lon_pixel_label
  LABL_PTR_3: rectangular_lat_pixel_label

base_agnostic_map: &base_agnostic_map
  DEPEND_0: epoch
  DEPEND_1: rectangular_lon_pixel
  DEPEND_2: rectangular_lat_pixel
  DISPLAY_TYPE: image
  FIELDNAM: " "
  FILLVAL: *int_fillval
  FORMAT: E10.3
  LABLAXIS: "Longitude / Latitude"
  LABL_PTR_1: rectangular_lon_pixel_label
  LABL_PTR_2: rectangular_lat_pixel_label
  VALIDMAX: *int_maxval
  VALIDMIN: 0
  VAR_TYPE: data

# Label attributes
rectangular_lon_pixel_label:
  CATDESC: Longitude pixel index label for IDEX SkyMap.
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Longitude pixel label
  FORMAT: A5
  VAR_TYPE: metadata

rectangular_lat_pixel_label:
  CATDESC: Latitude pixel index label for IDEX SkyMap.
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Latitude pixel label
  FORMAT: A5
  VAR_TYPE: metadata

# Vars
rectangular_lon_pixel:
  CATDESC: Longitude pixel center for IDEX SkyMap
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Rectangular Longitude Center
  FILLVAL: *double_fillval
  FORMAT: F12.6
  LABLAXIS: Longitude Pixel
  UNITS: degrees
  VALIDMAX: 360
  VALIDMIN: 0
  VAR_TYPE: support_data

rectangular_lat_pixel:
  CATDESC: Latitude pixel center for IDEX SkyMap
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Rectangular Latitude Center
  FILLVAL: *double_fillval
  FORMAT: F12.6
  LABLAXIS: Latitude Pixel
  UNITS: degrees
  VALIDMAX: 90
  VALIDMIN: -90
  VAR_TYPE: support_data

rate_by_charge_map:
  <<: *base_charge_map
  CATDESC: Count rate in s^-1 by impact charge, longitude, and latitude.
  DICT_KEY: SPASE>SupportQuantity:CountRate,Qualifier:Array
  FIELDNAM: Rate by Charge Map
  FILLVAL: *double_fillval
  UNITS: s^-1

counts_by_charge_map:
  <<: *base_charge_map
  CATDESC: Count by impact charge, longitude, and latitude.
  DICT_KEY: SPASE>Particle>ParticleType:Dust,ParticleQuantity:Counts,Qualifier:Array
  FIELDNAM: Counts by Charge Map
  FORMAT: I8
  UNITS: counts

counts_by_mass_map:
  <<: *base_mass_map
  CATDESC: Count by mass, longitude, and latitude.
  DICT_KEY: SPASE>Particle>ParticleType:Dust,ParticleQuantity:Counts,Qualifier:Array
  FIELDNAM: Counts by Mass Map
  FORMAT: I8
  UNITS: counts

rate_by_mass_map:
  <<: *base_mass_map
  CATDESC: Count rate in s^-1 by mass, longitude, and latitude.
  DICT_KEY: SPASE>SupportQuantity:CountRate,Qualifier:Array
  FIELDNAM: Rate by Mass Map
  FILLVAL: *double_fillval
  UNITS: s^-1

counts_map:
  <<: *base_agnostic_map
  CATDESC: Count of dust impacts by longitude and latitude.
  DICT_KEY: SPASE>Particle>ParticleType:Dust,ParticleQuantity:Counts,Qualifier:Array
  FIELDNAM: Counts Map
  FORMAT: I8
  UNITS: counts

rate_map:
  <<: *base_agnostic_map
  CATDESC: Dust impact count rate by longitude and latitude.
  DICT_KEY: SPASE>SupportQuantity:CountRate,Qualifier:Array
  FIELDNAM: Rate Map
  FILLVAL: *double_fillval
  UNITS: s^-1


on_off_times:
    CATDESC: Science acquisition on/off event times.
    CDF_DATA_TYPE: "CDF_TIME_TT2000"
    DICT_KEY: SPASE>Support>SupportQuantity:Temporal
    FIELDNAM: On/Off Times
    FILLVAL: -9223372036854775808
    FORMAT: " "
    LABLAXIS: On/Off Times
    MONOTON: INCREASE
    REFERENCE_POSITION: Rotating Earth Geoid
    RESOLUTION: ' '
    SCALETYP: linear
    TIME_BASE: J2000
    TIME_SCALE: Terrestrial Time
    UNITS: ns
    VALIDMAX: 3155716869184000000
    VALIDMIN: 315576066184000000
    VAR_TYPE: support_data

on_off_events:
  CATDESC: Science acquisition on/off event values (1 = on, 0 = off).
  DEPEND_0: on_off_times
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: On/Off Events
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: On/Off Events
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: support_data
