int_fillval: &int_fillval -9223372036854775808
max_uint32: &max_uint32 4294967295
max_uint32_min_one: &max_uint32_min_one 4294967294
max_uint16: &max_uint16 65535
min_epoch: &min_epoch -315575942816000000

bins_label:
  CATDESC: Label names for histogram bin numbers
  FIELDNAM: Label name
  FORMAT: A4
  VAR_TYPE: metadata

flags_label:
#  CATDESC: L1B flag identifier for daily-occurrence counter
  CATDESC: Flag names for daily-occurrence counters of L1B flags
  FIELDNAM: L1B flag name
  FORMAT: A42
  VAR_TYPE: metadata

default_attrs: &default_attrs
  # TODO: Remove unneeded attributes once SAMMI is fixed
  DISPLAY_TYPE: no_plot
  FILLVAL: *int_fillval
  UNITS: ' '
  VALIDMIN: *min_epoch

support_data_defaults: &support_data_defaults
  <<: *default_attrs
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FORMAT: I10
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: support_data

# UTC Strings
time_data_defaults: &time_data_defaults
  <<: *support_data_defaults
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal
  FILLVAL: ' '
  FORMAT: A30
  REFERENCE_POSITION: Rotating Earth Geoid
  RESOLUTION: ISO8601
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  UNITS: N/A
  VALIDMAX: ' '
  VALIDMIN: ' '

lightcurve_defaults: &lightcurve_defaults
  <<: *support_data_defaults
  DEPEND_1: bins
  DISPLAY_TYPE: no_plot
  LABL_PTR_1: bins_label
  VAR_TYPE: data

  derived_from_spice_kernels: &derived_from_spice_kernels
    VAR_NOTES: Derived from SPICE Kernels

bins_dim:
  <<: *default_attrs
  CATDESC: Histogram bin number
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Bin number
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: Bin no.
  MONOTON: INCREASE
  SCALETYP: linear
  VALIDMAX: 3599
  VALIDMIN: 0
  VAR_TYPE: support_data

flags_dim:
  <<: *default_attrs
  CATDESC: Flag index for daily-occurrence counters of L1B flags
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: L1B flag index
  FILLVAL: 255
  FORMAT: I2
  LABLAXIS: Index
  UNITS: ' '
  VALIDMAX: 16
  VALIDMIN: 0
  VAR_TYPE: support_data

ecliptic_dim:
  <<: *default_attrs
  # TODO: Update validmin and validmax
  CATDESC: Component index for cartesian ecliptic coordinates
  DICT_KEY: SPASE>Support>SupportQuantity:Orientation
  FIELDNAM: Component index
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: Index
  UNITS: ' '
  VALIDMAX: 2
  VALIDMIN: 0
  VAR_TYPE: support_data


number_of_good_l1b_inputs:
  <<: *support_data_defaults
  CATDESC: Number of good L1B inputs per observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Number of good L1B inputs
  FILLVAL: -9223372036854775808
  FORMAT: I5
  LABLAXIS: No. of L1B
  VALIDMAX: 20000 # 3 days * 86400 s / 14.6 s rounded up

total_l1b_inputs:
  <<: *support_data_defaults
  CATDESC: Total number of L1B inputs per observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Total number of L1B inputs
  FILLVAL: -9223372036854775808
  FORMAT: I5
  LABLAXIS: No. of L1B
  VALIDMAX: 20000

identifier:
  <<: *support_data_defaults
  CATDESC: Spin-axis pointing number to identify observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal
  FIELDNAM: Spin-axis pointing number
  FILLVAL: -9223372036854775808
  FORMAT: I5
  LABLAXIS: Pointing no.
  VALIDMAX: 99999

flight_software_version:
  <<: *support_data_defaults
  CATDESC: GLOWS flight software version
  FIELDNAM: GLOWS flight software version
  FILLVAL: -9223372036854775808
  FORMAT: I8
  LABLAXIS: FSW ver
  VALIDMAX: 16777215

pkts_file_name:
  CATDESC: Name of L0 packets file data originated
  FIELDNAM: Packets File Name
  FILLVAL: ' '
  FORMAT: A49
  VAR_TYPE: metadata

start_time:
  <<: *time_data_defaults
  CATDESC: Start time (UTC) of observational day
  DISPLAY_TYPE: no_plot
  FIELDNAM: Observation start time UTC
  LABLAXIS: N/A

end_time:
  <<: *time_data_defaults
  CATDESC: End time (UTC) of observational day
  DISPLAY_TYPE: no_plot
  FIELDNAM: Observation end time UTC
  LABLAXIS: N/A

filter_temperature_average:
  <<: *support_data_defaults
  CATDESC: Filter temperature averaged over observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Average filter temperature
  FILLVAL: -1.0E+31
  FORMAT: F6.2
  LABLAXIS: Temp
  UNITS: Celsius
  VALIDMAX: 60.0
  VALIDMIN: -30.0

filter_temperature_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation of filter temperature
  DICT_KEY: SPASE>Support>SupportQuantity:Housekeeping
  FIELDNAM: Std dev of filter temperature
  FILLVAL: -1.0E+31
  FORMAT: E9.3
  LABLAXIS: Temp std dev
  UNITS: Celsius
  VALIDMAX: 90.0
  VALIDMIN: 0.0

hv_voltage_average:
  <<: *support_data_defaults
  CATDESC: CEM HV voltage averaged over observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Housekeeping
  FIELDNAM: Average HV voltage
  FILLVAL: -1.0E+31
  FORMAT: F7.2
  LABLAXIS: HV
  UNITS: V
  VALIDMAX: 3500.0
  VALIDMIN: 0.0

hv_voltage_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation of CEM HV voltage
  DICT_KEY: SPASE>Support>SupportQuantity:Housekeeping
  FIELDNAM: Std dev of HV voltage
  FILLVAL: -1.0E+31
  FORMAT: E9.3
  LABLAXIS: HV std dev
  UNITS: V
  VALIDMAX: 3500.0
  VALIDMIN: 0.0

spin_period_average:
  <<: *support_data_defaults
  #DEPEND_0: epoch
  #DISPLAY_TYPE: time_series
  CATDESC: Spin period averaged over observational day
  DICT_KEY: SPASE>Support>SupportQuantity:SpinPeriod
  FIELDNAM: Average spin period
  FILLVAL: -1.0E+31
  FORMAT: F9.6
  LABLAXIS: Period
  UNITS: s
  VALIDMAX: 15.4
  VALIDMIN: 14.6

spin_period_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation of spin period
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Std dev of spin period
  FILLVAL: -1.0E+31
  FORMAT: E9.3
  LABLAXIS: Period std dev
  UNITS: s
  VALIDMAX: 9.9
  VALIDMIN: 0.0

# TODO review these
spin_period_ground_average:
  <<: *support_data_defaults
  #DEPEND_0: epoch
  #DISPLAY_TYPE: time_series
  CATDESC: Spin period (ground processing) averaged over observational day
  DICT_KEY: SPASE>Support>SupportQuantity:SpinPeriod
  FIELDNAM: Average spin period (ground)
  FILLVAL: -1.0E+31
  FORMAT: F9.6
  LABLAXIS: Period
  UNITS: s
  VALIDMAX: 15.4
  VALIDMIN: 14.6

spin_period_ground_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation of spin period (ground processing)
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Std dev of spin period (ground)
  FILLVAL: -1.0E+31
  FORMAT: E9.3
  LABLAXIS: Period std dev
  UNITS: s
  VALIDMAX: 9.9
  VALIDMIN: 0.0

pulse_length_average:
  <<: *support_data_defaults
  CATDESC: Pulse length averaged over observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Housekeeping
  FIELDNAM: Average pulse length
  FILLVAL: -1.0e+31
  FORMAT: F5.2
  LABLAXIS: Pulse
  UNITS: us
  VALIDMAX: 12.75
  VALIDMIN: 0.0

pulse_length_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation of pulse length
  DICT_KEY: SPASE>Support>SupportQuantity:Housekeeping
  FIELDNAM: Std dev of pulse length
  FILLVAL: -1.0e+31
  FORMAT: E9.3
  LABLAXIS: Pulse std dev
  UNITS: us
  VALIDMAX: 12.75
  VALIDMIN: 0.0

position_angle_offset_average:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Position angle offset averaged over observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Average position angle offset
  FILLVAL: -1.0e+31
  FORMAT: F10.6
  LABLAXIS: Offset angle
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0

position_angle_offset_std_dev:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Standard deviation of position angle offset
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Std dev of position angle offset
  FILLVAL: -1.0e+31
  FORMAT: E9.3
  LABLAXIS: Offset std dev
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0

spin_axis_orientation_average:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Spin axis pointing averaged over observational day (ecliptic lon and lat)
  DICT_KEY: SPASE>Support>SupportQuantity:SpinPhase
  FIELDNAM: Average spin axis pointing
  FILLVAL: -1.0e+31
  FORMAT: F7.3
  LABLAXIS: Lon/lat
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: -90.0

spin_axis_orientation_std_dev:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Standard deviation of spin axis pointing
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Std dev of spin axis pointing
  FILLVAL: -1.0e+31
  FORMAT: E9.3
  LABLAXIS: Lon/lat std dev
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0

spacecraft_location_average:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Spacecraft location averaged over observational day (ecliptic frame)
  DEPEND_1: ecliptic
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  DISPLAY_TYPE: no_plot
  FIELDNAM: Average spacecraft location
  FILLVAL: -1.0e+31
  FORMAT: E13.6
  LABLAXIS: Loc
  UNITS: km
  VALIDMAX: 9.999999999E+8
  VALIDMIN: -9.999999999E+8

spacecraft_location_std_dev:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Standard deviation of spacecraft location
  DEPEND_1: ecliptic
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: no_plot
  FIELDNAM: Std dev of spacecraft location
  FILLVAL: -1.0E+31
  FORMAT: E9.3
  LABLAXIS: Loc std dev
  UNITS: km
  VALIDMAX: 1.5E+7 # 50 km/s * 3 days * 86400 s < 1.5e7
  VALIDMIN: 0.0

spacecraft_velocity_average:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Spacecraft velocity averaged over observational day (ecliptic frame)
  DEPEND_1: ecliptic
  DICT_KEY: SPASE>Support>SupportQuantity:Velocity
  DISPLAY_TYPE: no_plot
  FIELDNAM: Average spacecraft velocity
  FILLVAL: -1.0E+31
  FORMAT: E13.6
  LABLAXIS: Vsc
  UNITS: km/s
  VALIDMAX: 50.0
  VALIDMIN: -50.0

spacecraft_velocity_std_dev:
  <<: *support_data_defaults
  <<: *derived_from_spice_kernels
  CATDESC: Standard deviation of spacecraft velocity
  DEPEND_1: ecliptic
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: no_plot
  FIELDNAM: Std dev of spacecraft velocity
  FILLVAL: -1.0E+31
  FORMAT: E9.3
  LABLAXIS: Vsc std dev
  UNITS: km/s
  VALIDMAX: 9.9
  VALIDMIN: 0.0

bad_time_flag_occurrences:
  <<: *support_data_defaults
  CATDESC: Numbers of occurences for each bad-time flag during observational day
  DEPEND_1: flags
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: no_plot
  FIELDNAM: Occurrences of bad-time flags
  FILLVAL: 65535
  FORMAT: I5
  LABLAXIS: No. of cases
  LABL_PTR_1: flags_label # MS: I do not understand this
  VALIDMAX: 65535
  VALIDMIN: 0
  VAR_TYPE: data

spin_angle:
  <<: *lightcurve_defaults
  CATDESC: Spin angle (measured from north) for bin centers
  DICT_KEY: SPASE>Support>SupportQuantity:SpinPhase
  FIELDNAM: Spin angle for bin centers
  FILLVAL: -1.0E+31
  FORMAT: F7.3
  LABLAXIS: Spin angle
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

photon_flux:
  <<: *lightcurve_defaults
  CATDESC: Photon flux in scanning-circle bins averaged over observational day
  DELTA_MINUS_VAR: flux_uncertainties
  DELTA_PLUS_VAR: flux_uncertainties
  DICT_KEY: SPASE>Wave>WaveType:Electromagnetic,WaveQuantity:Intensity,Qualifier:Scalar
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Pointing-averaged photon flux
  FILLVAL: -1.0E+31
  FORMAT: F8.2
  LABLAXIS: Flux
  UNITS: Rayleigh
  VALIDMAX: 30000.0 # max 30000 cps in FDIR / from 1 to 3.37 cps-per-R
  VALIDMIN: 0.0
  # uncertainties are symmetrcial, so same value is used for +/-
  # SPASE data pulled from TWINS 1 LAD metadata

raw_histograms:
  <<: *lightcurve_defaults
  CATDESC: Histogram of counts for observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Histogram of counts
  FILLVAL: -9223372036854775808
  FORMAT: I8
  LABLAXIS: Counts
  UNITS: '#'
  VALIDMAX: 35000000 # max 30000 cps in FDIR * 3 days * 86400 s / 225 bins rounded up
  VALIDMIN: 0

exposure_times:
  <<: *lightcurve_defaults
  CATDESC: Exposure times for histogram bins for observational day
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Exposure time per bin
  FILLVAL: -1.0E+31
  FORMAT: F7.2
  LABLAXIS: Bin exposure
  UNITS: s
  VALIDMAX: 1200.0 # 3 days * 86400 s / 225 bins rounded up
  VALIDMIN: 0.0

flux_uncertainties:
  <<: *lightcurve_defaults
  CATDESC: Statistical uncertainties for photon flux
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Photon flux uncertainties
  FILLVAL: -1.0E+31
  FORMAT: F8.2
  LABLAXIS: Flux uncert
  UNITS: Rayleigh
  VALIDMAX: 30000.0 # the same VALIDMAX as for photon_flux assumed
  VALIDMIN: 0.0
  VAR_TYPE: support_data

histogram_flag_array:
  <<: *lightcurve_defaults
  CATDESC: Bad-angle flags for histogram bins
  CDF_DATA_TYPE: CDF_UINT1
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Bad-angle flags for histogram
  FILLVAL: 255
  FORMAT: I2
  LABLAXIS: Mask value
  UNITS: ' '
  VALIDMAX: 15 # only 4 bits currently used
  VALIDMIN: 0
  VAR_TYPE: data

ecliptic_lon:
  <<: *lightcurve_defaults
  CATDESC: Ecliptic longitudes of bin centers
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Ecliptic longitudes of bins
  FILLVAL: -1.0E+31
  FORMAT: F7.3
  LABLAXIS: Bin lon
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

ecliptic_lat:
  <<: *lightcurve_defaults
  CATDESC: Ecliptic latitudes of bin centers
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Ecliptic latitudes of bins
  FILLVAL: -1.0E+31
  FORMAT: F7.3
  LABLAXIS: Bin lat
  UNITS: degrees
  VALIDMAX: 90.0
  VALIDMIN: -90.0
  VAR_TYPE: support_data

number_of_bins:
  <<: *support_data_defaults
  CATDESC: Number of bins in histogram
  CDF_DATA_TYPE: CDF_UINT2
  DICT_KEY: SPASE>Support>SupportQuantity:Other
  FIELDNAM: Number of bins in histogram
  FILLVAL: *max_uint16
  FORMAT: I4
  LABLAXIS: No. of bins
  UNITS: ' '
  VALIDMAX: 3600
  VALIDMIN: 225
  VAR_TYPE: support_data
