default_attrs: &default
  # Assumed values for all variable attrs unless overwritten
  DISPLAY_TYPE: no_plot
  FILLVAL: -9223372036854775808
  FORMAT: I12
  UNITS: dN
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  VAR_TYPE: data
  SCALETYP: linear

codice_support_attrs: &support_default
    <<: *default
    VAR_TYPE: support_data

acquisition_times_attrs:
    <<: *default
    CATDESC: Time of acquisition for the energy step
    FIELDNAM: Acquisition Time
    FILLVAL: -1e+31
    FORMAT: F10.3
    LABLAXIS: Acq Time
    UNITS: ms
    VALIDMIN: 0
    VALIDMAX: 1.7976931348623157e+308
    VAR_TYPE: support_data

counters_attrs:
    <<: *default
    CATDESC: Fill in at creation
    DEPEND_0: epoch
    DEPEND_1: energy
    DISPLAY_TYPE: time_series
    FIELDNAM: Fill in at creation
    LABL_PTR_1: energy
    UNITS: counts
    VALIDMIN: 0
    VALIDMAX: 8388607  # max value for a signed 24-bit integer

energy_attrs:
    <<: *default
    CATDESC: Energy per charge (E/q) sweeping step
    FIELDNAM: Energy step
    FORMAT: I3
    LABLAXIS: energy
    UNITS: dN
    VALIDMIN: 0
    VALIDMAX: 127
    VAR_TYPE: support_data

esa_sweep_attrs:
    <<: *default
    CATDESC: ElectroStatic Analyzer Energy Values
    FIELDNAM: ESA Voltage
    FORMAT: I19
    LABLAXIS: ESA V
    UNITS: V
    VALIDMIN: 0
    VAR_TYPE: support_data

# TODO: Define CATDESCs and FIELDNAMs for metadata fields, e.g.:
#COMPRESSION:
#    <<: *support_default
#    CATDESC: Indicates if the data is compressed, with 1 indicating the data is compressed
#    FIELDNAM: Data is compressed