default_attrs: &default
  # Assumed values for all variable attrs unless overwritten
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  VAR_TYPE: data
  UNITS: " "

component:
  CATDESC: Component direction (x, y, z)
  FIELDNAM: Vector component
  LABLAXIS: Component
  FORMAT: A3
  VAR_TYPE: metadata
  UNITS: " "

RTN_component:
  CATDESC: Component direction (radial, tangential, normal)
  FIELDNAM: RTN vector component
  LABLAXIS: RTN component
  FORMAT: A3
  VAR_TYPE: metadata
  UNITS: " "

esa_step:
  CATDESC: ESA step number. The nominal central energies for the 8 i-ALiRT channels are 100.4, 140, 194, 270, 376, 523, 727, and 1011 eV.
  FIELDNAM: ESA step index
  LABLAXIS: ESA step
  FORMAT: I2
  VALIDMIN: 0
  VALIDMAX: 7
  VAR_TYPE: metadata
  UNITS: " "

codice_hi_h_spin_angle:
    CATDESC: CoDICE-Hi spin angle bin
    FIELDNAM: CoDICE-Hi spin angle bin
    LABLAXIS: Spin angle bin
    FORMAT: I3
    VALIDMIN: 0
    VALIDMAX: 3
    VAR_TYPE: metadata
    UNITS: " "

codice_hi_h_energy_range:
    CATDESC: CoDICE-Hi H energy range
    FIELDNAM: CoDICE-Hi H energy range
    LABLAXIS: Energy range
    FORMAT: I3
    VALIDMIN: 0
    VALIDMAX: 14
    VAR_TYPE: metadata
    UNITS: " "

codice_hi_h_spin_sector:
    CATDESC: CoDICE-Hi spin sector
    FIELDNAM: CoDICE-Hi spin sector
    LABLAXIS: Spin sector
    FORMAT: I3
    VALIDMIN: 0
    VALIDMAX: 3
    VAR_TYPE: metadata
    UNITS: " "

codice_hi_h_azimuth:
    CATDESC: CoDICE-Hi azimuth bin
    FIELDNAM: CoDICE-Hi azimuth bin
    LABLAXIS: Azimuth bin
    FORMAT: I3
    VALIDMIN: 0
    VALIDMAX: 3
    VAR_TYPE: metadata
    UNITS: " "

default_uint8_attrs: &default_uint8
  <<: *default
  FILLVAL: 255
  FORMAT: I3
  VALIDMIN: 0
  VALIDMAX: 255
  dtype: uint8

default_uint16_attrs: &default_uint16
  <<: *default
  FILLVAL: 65535
  FORMAT: I5
  VALIDMIN: 0
  VALIDMAX: 65535
  dtype: uint16

default_uint32_attrs: &default_uint32
  <<: *default
  FILLVAL: 4294967295
  FORMAT: I10
  VALIDMIN: 0
  VALIDMAX: 4294967295
  dtype: uint32

default_int64_attrs: &default_int64
  <<: *default
  FILLVAL: -9223372036854775808
  FORMAT: I20
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  dtype: int64

default_int32_attrs: &default_int32
  <<: *default
  FILLVAL: -2147483648
  FORMAT: I10
  VALIDMIN: -2147483648
  VALIDMAX: 2147483647
  dtype: int32

default_float32_attrs: &default_float32
  <<: *default
  FILLVAL: -1.0e31
  FORMAT: F12.6
  VALIDMIN: -3.4028235e+38
  VALIDMAX: 3.4028235e+38
  dtype: float32

default_float64_attrs: &default_float64
  <<: *default
  FILLVAL: -1.0e31
  FORMAT: F10.2
  VALIDMIN: -1.7976931348623157e+308
  VALIDMAX: 1.7976931348623157e+308
  dtype: float64

codice_hi_h:
  <<: *default_float32
  CATDESC: H intensity in 4 spin angle bins, 15 energy ranges, 4 spin sector bins, and 4 azimuth bins
  FIELDNAM: H intensity
  LABLAXIS: H intensity
  UNITS: "# / cm2-sr-s- MeV"
  VALIDMIN: 0
  VALIDMAX: 100000000.0
  DEPEND_1: codice_hi_h_spin_angle
  DEPEND_2: codice_hi_h_energy_range
  DEPEND_3: codice_hi_h_spin_sector
  DEPEND_4: codice_hi_h_azimuth
  VAR_NOTES: Energy ranges (MeV) are 0.0200–0.0283, 0.0283–0.0400, 0.0400–0.0566, 0.0566–0.0800, 0.0800–0.113, 0.113–0.160, 0.160–0.226, 0.226–0.320, 0.320–0.453, 0.453–0.640, 0.640–0.905, 0.905–1.28, 1.28–1.81, 1.81–2.56, 2.56–3.62.

codice_lo_c_over_o_abundance:
  <<: *default_float32
  CATDESC: C/O abundance ratio
  FIELDNAM: C/O abundance ratio
  LABLAXIS: C/O ratio
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 100000000.0

codice_lo_mg_over_o_abundance:
  <<: *default_float32
  CATDESC: Mg/O abundance ratio
  FIELDNAM: Mg/O abundance ratio
  LABLAXIS: Mg/O ratio
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 100000000.0

codice_lo_fe_over_o_abundance:
  <<: *default_float32
  CATDESC: Fe/O abundance ratio
  FIELDNAM: Fe/O abundance ratio
  LABLAXIS: Fe/O ratio
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 100000000.0

codice_lo_c_plus_6_over_c_plus_5_ratio:
  <<: *default_float32
  CATDESC: C+6/C+5 charge state ratio
  FIELDNAM: C6+/C5+ charge ratio
  LABLAXIS: C6+/C5+
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 100000000.0

codice_lo_o_plus_7_over_o_plus_6_ratio:
  <<: *default_float32
  CATDESC: O+7/O+6 charge state ratio
  FIELDNAM: O7+/O6+ charge ratio
  LABLAXIS: O7+/O6+
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 100000000.0

codice_lo_fe_low_over_fe_high_ratio:
  <<: *default_float32
  CATDESC: Fe low/high charge state ratio (low=6–12, high=13–17)
  FIELDNAM: Fe low/high charge ratio
  LABLAXIS: Fe low/high
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 100000000.0

hit_e_a_side_low_en:
  <<: *default_uint32
  CATDESC: Low energy (>0.5 MeV) electrons (A-side)
  FIELDNAM: Electrons low energy (A-side)
  LABLAXIS: e- low energy (A)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_e_a_side_med_en:
  <<: *default_uint32
  CATDESC: Medium energy (<1 MeV) electrons (A-side)
  FIELDNAM: Electrons medium energy (A-side)
  LABLAXIS: e- medium energy (A)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_e_a_side_high_en:
  <<: *default_uint32
  CATDESC: High energy (>3 MeV) electrons (A-side)
  FIELDNAM: Electrons high energy (A-side)
  LABLAXIS: e- high energy (A)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_e_b_side_low_en:
  <<: *default_uint32
  CATDESC: Low energy (>0.5 MeV) electrons (B-side)
  FIELDNAM: Electrons low energy (B-side)
  LABLAXIS: e- low energy (B)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_e_b_side_med_en:
  <<: *default_uint32
  CATDESC: Medium energy (<1 MeV) electrons (B-side)
  FIELDNAM: Electrons medium energy (B-side)
  LABLAXIS: e- medium energy (B)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_e_b_side_high_en:
  <<: *default_uint32
  CATDESC: High energy (>3 MeV) electrons (B-side)
  FIELDNAM: Electrons high energy (B-side)
  LABLAXIS: e- high energy (B)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_h_omni_low_en:
  <<: *default_uint32
  CATDESC: Low energy (6–8 MeV) protons (omnidirectional)
  FIELDNAM: Protons 6–8 MeV (omni)
  LABLAXIS: H 6–8 MeV (omni)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000

hit_h_omni_med_en:
  <<: *default_uint32
  CATDESC: Medium energy (12–15 MeV) protons (omnidirectional)
  FIELDNAM: Protons 12–15 MeV (omni)
  LABLAXIS: H 12–15 MeV (omni)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000

hit_h_a_side_high_en:
  <<: *default_uint32
  CATDESC: High energy (>70 MeV) protons (A-side)
  FIELDNAM: Protons >70 MeV (A-side)
  LABLAXIS: H >70 MeV (A-side)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_h_b_side_high_en:
  <<: *default_uint32
  CATDESC: High energy (>70 MeV) protons (B-side)
  FIELDNAM: Protons >70 MeV (B-side)
  LABLAXIS: H >70 MeV (B-side)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000
  VAR_NOTES: A-side indicates the HIT aperture that is nominally looking in the anti-sunward direction. B-side indicates the aperture looking nominally in the sunward direction.

hit_he_omni_low_en:
  <<: *default_uint32
  CATDESC: Low energy (6–8 MeV/nuc) helium (omnidirectional)
  FIELDNAM: Helium 6–8 MeV/nuc (omni)
  LABLAXIS: He 6–8 MeV/nuc (omni)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000

hit_he_omni_high_en:
  <<: *default_uint32
  CATDESC: High energy (15–70 MeV/nuc) helium (omnidirectional)
  FIELDNAM: Helium 15–70 MeV/nuc (omni)
  LABLAXIS: He 15–70 MeV/nuc (omni)
  UNITS: counts per second
  VALIDMIN: 0
  VALIDMAX: 1000000000

mag_epoch:
  <<: *default_float32
  CATDESC: MAG instrument epoch time tag
  FIELDNAM: MAG epoch
  LABLAXIS: MAG epoch
  UNITS: ns
  VALIDMIN: 0.0
  VALIDMAX: 9223372036854775807.0

mag_B_GSE:
  <<: *default_float32
  CATDESC: Magnetic field vector in GSE coordinates
  FIELDNAM: Magnetic field in GSE
  LABLAXIS: B (GSE)
  LABL_PTR_1: component
  UNITS: nT
  DEPEND_1: component
  VALIDMIN: -65000.0
  VALIDMAX: 65000.0

mag_B_GSM:
  <<: *default_float32
  CATDESC: Magnetic field vector in GSM coordinates
  FIELDNAM: Magnetic field in GSM
  LABLAXIS: B (GSM)
  LABL_PTR_1: component
  UNITS: nT
  DEPEND_1: component
  VALIDMIN: -65000.0
  VALIDMAX: 65000.0

mag_B_RTN:
  <<: *default_float32
  CATDESC: Magnetic field vector in RTN coordinates
  FIELDNAM: Magnetic field in RTN
  LABLAXIS: B (RTN)
  LABL_PTR_1: RTN_component
  UNITS: nT
  DEPEND_1: RTN_component
  VALIDMIN: -65000.0
  VALIDMAX: 65000.0

mag_B_magnitude:
  <<: *default_float32
  CATDESC: Magnitude of the magnetic field vector
  FIELDNAM: Magnetic field magnitude
  LABLAXIS: B Magnitude
  UNITS: nT
  VALIDMIN: 0.0
  VALIDMAX: 65000.0

mag_phi_B_GSM:
  <<: *default_float32
  CATDESC: Azimuth angle (φ) of the magnetic field in GSM coordinates
  FIELDNAM: B azimuth angle in GSM
  LABLAXIS: B azimuth (GSM)
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0

mag_theta_B_GSM:
  <<: *default_float32
  CATDESC: Elevation angle (θ) of the magnetic field in GSM coordinates
  FIELDNAM: B elevation angle in GSM
  LABLAXIS: B elevation (GSM)
  UNITS: degrees
  VALIDMIN: -90.0
  VALIDMAX: 90.0

mag_phi_B_GSE:
  <<: *default_float32
  CATDESC: Azimuth angle (φ) of the magnetic field in GSE coordinates
  FIELDNAM: B azimuth angle in GSE
  LABLAXIS: B azimuth (GSE)
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0

mag_theta_B_GSE:
  <<: *default_float32
  CATDESC: Elevation angle (θ) of the magnetic field in GSE coordinates
  FIELDNAM: B elevation angle in GSE
  LABLAXIS: B elevation (GSE)
  UNITS: degrees
  VALIDMIN: -90.0
  VALIDMAX: 90.0

sc_position_GSM:
  <<: *default_float32
  CATDESC: Spacecraft position vector in GSM coordinates
  FIELDNAM: Spacecraft position in GSM
  LABLAXIS: SC position (GSM)
  UNITS: km
  DEPEND_1: component
  VALIDMIN: -3000000.0
  VALIDMAX: 3000000.0

sc_velocity_GSM:
  <<: *default_float32
  CATDESC: Spacecraft velocity vector in GSM coordinates
  FIELDNAM: Spacecraft velocity in GSM
  LABLAXIS: SC velocity (GSM)
  UNITS: km/s
  DEPEND_1: component
  VALIDMIN: -1000.0
  VALIDMAX: 1000.0

sc_position_GSE:
  <<: *default_float32
  CATDESC: Spacecraft position vector in GSE coordinates
  FIELDNAM: Spacecraft position in GSE
  LABLAXIS: SC position (GSE)
  UNITS: km
  DEPEND_1: component
  VALIDMIN: -3000000.0
  VALIDMAX: 3000000.0

sc_velocity_GSE:
  <<: *default_float32
  CATDESC: Spacecraft velocity vector in GSE coordinates
  FIELDNAM: Spacecraft velocity in GSE
  LABLAXIS: SC velocity (GSE)
  UNITS: km/s
  DEPEND_1: component
  VALIDMIN: -1000.0
  VALIDMAX: 1000.0

swapi_pseudo_proton_density:
  <<: *default_float32
  CATDESC: Pseudo density of solar wind protons
  FIELDNAM: SW proton pseudo density
  LABLAXIS: proton density
  UNITS: 1/cm^3
  VALIDMIN: 0.0
  VALIDMAX: 1000.0

swapi_pseudo_proton_speed:
  <<: *default_float32
  CATDESC: Pseudo speed of solar wind protons in solar inertial frame
  FIELDNAM: SW proton pseudo speed
  LABLAXIS: proton speed
  UNITS: km/sec
  VALIDMIN: 0.0
  VALIDMAX: 10000.0

swapi_pseudo_proton_temperature:
  <<: *default_float32
  CATDESC: Pseudo temperature of solar wind protons in plasma frame
  FIELDNAM: SW proton pseudo temperature
  LABLAXIS: proton temperature
  UNITS: Kelvin
  VALIDMIN: 0.0
  VALIDMAX: 50000000.0

# SWE Normalized Counts
swe_normalized_counts:
  <<: *default_uint32
  CATDESC: Normalized electron counts
  FIELDNAM: SWE normalized counts
  LABLAXIS: SWE norm counts
  UNITS: Normalized counts
  VALIDMIN: 0
  VALIDMAX: 500000
  DEPEND_1: esa_step
  VAR_NOTES: The nominal central energies for the 8 i-ALiRT channels are 100.4, 140, 194, 270, 376, 523, 727, and 1011 eV.

swe_counterstreaming_electrons:
  <<: *default_uint8
  CATDESC: Counterstreaming electrons flag (0=no, 1=yes)
  FIELDNAM: Counterstreaming electrons
  LABLAXIS: Counterstreaming e-
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 1
  VAR_NOTES: A value of 1 indicates that counterstreaming electrons were observed, a value of 0 indicates unidirectional electron flow.
