# By default the time is assumed to correspond to instantaneous time or
# center of accumulation/measurement period. But if, for some good reason,
# time corresponds to the beginning or end or any other part of
# accumulation/measurement period, that has to be stated in CATDESC.

epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  DICT_KEY: "SPASE>Support>SupportQuantity:Temporal"
  FIELDNAM: epoch
  FILLVAL: -9223372036854775808
  FORMAT: " " # Supposedly not required, fails in xarray_to_cdf
  LABLAXIS: epoch
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  RESOLUTION: ' '
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  UNITS: ns
  VALIDMAX: 3155716869184000000  # 2100-01-01T00:00:00 mission end
  VALIDMIN: 315576066184000000   # 2010-01-01T00:00:00 mission start (APL 0 epoch)
  VAR_TYPE: support_data


# <=== Data Variables ===>
# Default Attrs for all metadata variables unless overridden
metadata_attrs:
  DEPEND_0: epoch
  FILLVAL: -9223372036854775808
  FORMAT: I19
  LABLAXIS: ' '
  SCALETYP: linear
  UNITS: ' '
  VALIDMAX: 9223372036854769664
  VALIDMIN: 0
  VAR_TYPE: support_data
