int_fillval: &int_fillval -9223372036854775808
double_fillval: &double_fillval -1.0E31

data_min: &data_min 0
data_max: &data_max 4095
spice_data_min: &spice_data_min -2.0e7
spice_data_max: &spice_data_max 2.0e7

dead_max: &dead_max 4.065248492307693

# <=== Base Attributes ===>
string_base_attrs: &string_base
  CATDESC: " "
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: " "
  FORMAT: A3
  LABLAXIS: "none"
  UNITS: " "
  VAR_TYPE: metadata

l1b_data_base: &l1b_data_base
  CATDESC: ""
  DEPEND_0: epoch
  DISPLAY_TYPE: spectrogram
  FIELDNAM: ""
  FILLVAL: *double_fillval
  FORMAT: F12.6
  LABLAXIS: ""
  UNITS: pC
  VALIDMAX: *data_max
  VALIDMIN: *data_min
  VAR_TYPE: data

l1b_tof_base: &l1b_tof_base
  <<: *l1b_data_base
  DEPEND_1: time_high_sample_rate_index
  LABL_PTR_1: time_high_sample_rate_label
  UNITS: mA

l1b_target_base: &l1b_target_base
  <<: *l1b_data_base
  DEPEND_1: time_low_sample_rate_index
  LABL_PTR_1: time_low_sample_rate_label

trigger_base: &trigger_base
  <<: *l1b_data_base
  DISPLAY_TYPE: no_plot
  UNITS: " "

spice_base: &spice_base
  <<: *l1b_data_base
  DISPLAY_TYPE: time_series
  FORMAT: F16.6
  VALIDMAX: *spice_data_max
  VALIDMIN: *spice_data_min
  VAR_TYPE: data

# <=== Instrument Setting Attributes ===>
trigger_mode_lg:
  <<: *string_base
  CATDESC: Low Gain Trigger Mode.
  FIELDNAM: Low Gain Trigger Mode

trigger_level_lg:
  <<: *trigger_base
  CATDESC: Low Gain Trigger Level threshold.
  FIELDNAM: Low Gain Trigger Level
  UNITS: mA

trigger_mode_mg:
  <<: *string_base
  CATDESC: Mid Gain Trigger Mode.
  FIELDNAM: Mid Gain Trigger Mode

trigger_level_mg:
  <<: *trigger_base
  CATDESC: Mid Gain Trigger level threshold.
  FIELDNAM: Mid Gain Trigger Level
  UNITS: mA


trigger_mode_hg:
  <<: *string_base
  CATDESC: High Gain Trigger Mode.
  FIELDNAM: High Gain Trigger Mode

trigger_level_hg:
  <<: *trigger_base
  CATDESC: High Trigger Level threshold.
  FIELDNAM: High Trigger Level
  UNITS: mA

trigger_origin:
  <<: *string_base
  CATDESC: Trigger Origin of the event.
  FIELDNAM: Trigger Origin

pulser_on:
  <<: *trigger_base
  CATDESC: Pulser state flag derived from message events (0=off, 1=on).
  FIELDNAM: Pulser On
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: Pulser On
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: support_data

science_on:
  <<: *trigger_base
  CATDESC: Science acquisition state flag derived from message events (0=off, 1=on).
  FIELDNAM: Science On
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: Science On
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: support_data

tof_high:
  <<: *l1b_tof_base
  CATDESC: Time of flight waveform on the high-gain channel
  FIELDNAM: High Gain Time of Flight
  LABLAXIS: TOF High Ampl
  VAR_NOTES: High gain channel of the time-of-flight signal.
        Sampled at 260 Megasamples per second, with a 10-bit resolution.
        Data is used to quantify dust composition.

tof_mid:
  <<: *l1b_tof_base
  CATDESC: Time of flight waveform on the mid-gain channel
  FIELDNAM: Mid Gain Time of Flight
  LABLAXIS: TOF Mid Ampl
  VAR_NOTES: Mid gain channel of the time-of-flight signal.
        Sampled at 260 Megasamples per second, with a 10-bit resolution.
        Data is used to quantify dust composition.

tof_low:
  <<: *l1b_tof_base
  CATDESC: Time of flight waveform on the low-gain channel
  FIELDNAM: Low Gain Time of Flight
  LABLAXIS: TOF Low Ampl
  VAR_NOTES: Low gain channel of the time-of-flight signal.
        Sampled at 260 Megasamples per second, with a 10-bit resolution.
        Data is used to quantify dust composition.


target_low:
  <<: *l1b_target_base
  CATDESC: Target low charge sensitive amplifier waveform
  FIELDNAM: Low Target Signal
  LABLAXIS: Low Target Ampl
  VAR_NOTES: Low gain channel of IDEX's target signal.
        Sampled at 3.75 Msps with 12-bit resolution.
        Data is used to quantify dust charge.

target_high:
  <<: *l1b_target_base
  CATDESC: Ion grid charge sensitive amplifier waveform
  FIELDNAM: High Target Signal
  LABLAXIS: High Target Ampl
  VAR_NOTES: High gain channel of IDEX's target signal.
        Sampled at 3.75 Msps with 12-bit resolution.
        Data is used to quantify dust charge.

ion_grid:
  <<: *l1b_target_base
  CATDESC: Ion grid charge sensitive amplifier waveform data
  FIELDNAM: Ion Grid Signal
  LABLAXIS: Ion Grid Ampl
  VAR_NOTES: This is the ion grid signal from IDEX.
        Sampled at 3.75 Msps with 12-bit resolution.
        Data is used to quantify dust charge.

detector_voltage:
  <<: *trigger_base
  CATDESC: Voltage reading of Detector on HVPS Board (ADC Channel 0)
  FIELDNAM: Detector Voltage
  LABLAXIS: Voltage
  UNITS: V

sensor_voltage:
  <<: *trigger_base
  CATDESC: Voltage reading of Detector on HVPS Board (ADC Channel 0)
  FIELDNAM: Sensor Voltage
  LABLAXIS: Voltage
  UNITS: V

target_voltage:
  <<: *trigger_base
  CATDESC: Voltage reading of Target on HVPS Board  (ADC Channel 2)
  FIELDNAM: Target Voltage
  LABLAXIS: Voltage
  UNITS: V

reflectron_voltage:
  <<: *trigger_base
  CATDESC: Voltage reading of Reflectron on HVPS Board  (ADC Channel 3)
  FIELDNAM: Reflectron Voltage
  LABLAXIS: Voltage
  UNITS: V

rejection_voltage:
  <<: *trigger_base
  CATDESC: Voltage reading of Rejection on HVPS Board (ADC Channel 4)
  FIELDNAM: Rejection Voltage
  LABLAXIS: Voltage
  UNITS: V

current_hvps_sensor:
  <<: *trigger_base
  CATDESC: Reading of Detector current on HVPS Board (ADC Channel 5)
  FIELDNAM: Detector Current
  LABLAXIS: Current
  UNITS: mA

current_1v_pol:
  <<: *trigger_base
  CATDESC: High side current reading on 1.0V bus on Processor Board (ADC channel 0)
  FIELDNAM: 1V POL Current
  LABLAXIS: Current
  UNITS: mA

current_1p9v_pol:
  <<: *trigger_base
  CATDESC: High side current reading on 1.9V bus on Processor Board (ADC channel 1)
  FIELDNAM: 1.9V POL Current
  LABLAXIS: Current
  UNITS: mA

temperature_1:
  <<: *trigger_base
  CATDESC: Temperature reading near high speed ADCs on Processor Board (ADC channel 2)
  FIELDNAM: ProcBd Temp1
  FORMAT: F12.6
  LABLAXIS: Temperature
  UNITS: C

temperature_2:
  <<: *trigger_base
  CATDESC: Temperature reading near center of Processor Board (ADC channel 3)
  FIELDNAM: ProcBd Temp2
  FORMAT: F12.6
  LABLAXIS: Temperature
  UNITS: C

voltage_1v_bus:
  <<: *trigger_base
  CATDESC: Voltage reading of 1.0V bus on Processor Board (ADC channel 4)
  FIELDNAM: 1V Voltage
  LABLAXIS: Voltage
  UNITS: V

fpga_temperature:
  <<: *trigger_base
  CATDESC: Temperature reading on FPGA on Processor Board (ADC channel 5)
  FIELDNAM: FPGA Temp
  LABLAXIS: Temperature
  UNITS: C

voltage_1p9v_bus:
  <<: *trigger_base
  CATDESC: Voltage reading of 1.9V bus on Processor Board (ADC channel 6)
  FIELDNAM: 1.9V Voltage
  LABLAXIS: Voltage
  UNITS: V

voltage_3p3v_bus:
  <<: *trigger_base
  CATDESC: Voltage reading of 3.3V bus on Processor Board (ADC channel 7)
  FIELDNAM: 3.3V Voltage
  LABLAXIS: Voltage
  UNITS: V

positive_current_hvps:
  <<: *trigger_base
  CATDESC: Reading of HVPS Sensor positive current (ADC Channel 6)
  FIELDNAM: Sensor IP
  LABLAXIS: Current
  UNITS: mA

negative_current_hvps:
  <<: *trigger_base
  CATDESC: Reading of HVPS Sensor negative current (ADC Channel 7)
  FIELDNAM: Sensor IN
  LABLAXIS: Current
  UNITS: mA

voltage_3p3_ref:
  <<: *trigger_base
  CATDESC: Positive voltage reading on +3.3V bus Housekeeping reference on LVPS Board (ADC 0 channel 0)
  FIELDNAM: P3.3VREF_HK
  LABLAXIS: Voltage
  UNITS: V

voltage_3p3_op_ref:
  <<: *trigger_base
  CATDESC: Positive voltage reading on +3.3V bus Operations reference on LVPS Board (ADC 0 channel 1)
  FIELDNAM: P3.3VREF_OP
  LABLAXIS: Voltage
  UNITS: V

voltage_neg6v_bus:
  <<: *trigger_base
  CATDESC: Negative voltage reading on -6V bus on LVPS Board (ADC 0 channel 2)
  FIELDNAM: N6V
  LABLAXIS: Voltage
  UNITS: V

voltage_pos6v_bus:
  <<: *trigger_base
  CATDESC: Positive voltage reading on +6V bus on LVPS Board (ADC 0 channel 3)
  FIELDNAM: P6V
  LABLAXIS: Voltage
  UNITS: V

voltage_pos16v_bus:
  <<: *trigger_base
  CATDESC: Positive voltage reading on +16V bus on LVPS Board (ADC 0 channel 4)
  FIELDNAM: P16V
  LABLAXIS: Voltage
  UNITS: V

voltage_pos3p3v_bus:
  <<: *trigger_base
  CATDESC: Positive voltage reading on +3.3V bus on LVPS Board (ADC 0 channel 5)
  FIELDNAM: P3.3V
  LABLAXIS: Voltage
  UNITS: V

voltage_neg5v_bus:
  <<: *trigger_base
  CATDESC: Negative voltage reading on -5V bus on LVPS Board (ADC 0 channel 6)
  FIELDNAM: N5V
  LABLAXIS: Voltage
  UNITS: V

voltage_pos5v_bus:
  <<: *trigger_base
  CATDESC: Positive voltage reading on +5V bus on LVPS Board (ADC 0 channel 7)
  FIELDNAM: P5V
  LABLAXIS: Voltage
  UNITS: V

current_3p3v_bus:
  <<: *trigger_base
  CATDESC: Positive current reading on +3.3V bus on LVPS Board (ADC 1 channel 0)
  FIELDNAM: P3.3_IMON
  LABLAXIS: Current
  UNITS: A

current_16v_bus:
  <<: *trigger_base
  CATDESC: Positive current reading on +16V bus on LVPS Board (ADC 1 channel 1)
  FIELDNAM: P16V_IMON
  LABLAXIS: Current
  UNITS: A

current_6v_bus:
  <<: *trigger_base
  CATDESC: Positive current reading on +6V bus on LVPS Board (ADC 1 channel 2)
  FIELDNAM: P6V_IMON
  LABLAXIS: Current
  UNITS: A

current_neg6v_bus:
  <<: *trigger_base
  CATDESC: Negative current reading on -6V bus on LVPS Board (ADC 1 channel 3)
  FIELDNAM: N6V_IMON
  LABLAXIS: Current
  UNITS: A

current_5v_bus:
  <<: *trigger_base
  CATDESC: Positive current reading on +5V bus on LVPS Board (ADC 1 channel 4)
  FIELDNAM: P5V_IMON
  LABLAXIS: Current
  UNITS: A

current_neg5v_bus:
  <<: *trigger_base
  CATDESC: Negative current reading on -5V bus on LVPS Board (ADC 1 channel 5)
  FIELDNAM: N5V_IMON
  LABLAXIS: Current
  UNITS: A

current_2p5v_bus:
  <<: *trigger_base
  CATDESC: Positive current reading on +2.5V bus on LVPS Board (ADC 1 channel 6)
  FIELDNAM: P2.5V_IMON
  LABLAXIS: Current
  UNITS: A

current_neg2p5v_bus:
  <<: *trigger_base
  CATDESC: Negative current reading on -2.5V bus on LVPS Board (ADC 1 channel 7)
  FIELDNAM: N2.5V_IMON
  LABLAXIS: Current
  UNITS: A

# <=== Dead Time Attributes ===>
dead_time:
  <<: *l1b_data_base
  CATDESC: Event dead time
  DEPEND_0: epoch
  FIELDNAM: event_dead_time
  FILLVAL: *double_fillval
  FORMAT: F12.6
  LABLAXIS: event_dead_time
  UNITS: s
  VALIDMAX: *dead_max
  VALIDMIN: *data_min
  VAR_TYPE: data

# <=== Spice Data Attributes ===>
ephemeris_position_x:
  <<: *spice_base
  CATDESC: Cartesian coord X positions for the IMAP spacecraft in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Position X
  LABLAXIS: Position X
  UNITS: km

ephemeris_position_y:
  <<: *spice_base
  CATDESC: Cartesian coord Y positions for the IMAP spacecraft in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Position Y
  LABLAXIS: Position Y
  UNITS: km

ephemeris_position_z:
  <<: *spice_base
  CATDESC: Cartesian coord Z positions for the IMAP spacecraft in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  FIELDNAM: Position Z
  LABLAXIS: Position Z
  UNITS: km

ephemeris_velocity_x:
  <<: *spice_base
  CATDESC: Velocity X positions for the IMAP spacecraft in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Velocity
  FIELDNAM: Velocity X
  LABLAXIS: Velocity X
  UNITS: km/s

ephemeris_velocity_y:
  <<: *spice_base
  CATDESC: Velocity Y positions for the IMAP spacecraft in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Velocity
  FIELDNAM: Velocity Y
  LABLAXIS: Velocity Y
  UNITS: km/s

ephemeris_velocity_z:
  <<: *spice_base
  CATDESC: Velocity Z positions for the IMAP spacecraft in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Velocity
  FIELDNAM: Velocity Z
  LABLAXIS: Velocity Z
  UNITS: km/s


longitude:
  <<: *spice_base
  CATDESC: Longitude of the dust event as observed from Earth in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Longitude
  FIELDNAM: Longitude
  LABLAXIS: Longitude
  UNITS: Degrees
  VALIDMAX: 360
  VALIDMIN: 0

latitude:
  <<: *spice_base
  CATDESC: Latitude of the dust event as observed from Earth in the ECLIPJ2000 frame.
  DICT_KEY: SPASE>Support>SupportQuantity:Latitude
  FIELDNAM: Latitude
  LABLAXIS: Latitude
  UNITS: Degrees
  VALIDMAX: 90
  VALIDMIN: -90

spin_phase:
  <<: *spice_base
  CATDESC: IMAP Spin Phase
  DICT_KEY: SPASE>Support>SupportQuantity:SpinPhase
  FIELDNAM: Spin Phase
  FILLVAL: *double_fillval
  FORMAT: F8.3
  LABLAXIS: Spin Phase
  UNITS: Degrees
  VALIDMAX: 360
  VALIDMIN: 0

solar_longitude:
  <<: *spice_base
  CATDESC: Solar Longitude of the IMAP spacecraft
  DICT_KEY: SPASE>Support>SupportQuantity:Longitude
  FIELDNAM: Solar Longitude
  LABLAXIS: Solar Longitude
  UNITS: Degrees
  VALIDMAX: 180
  VALIDMIN: -180
