# ----------------------------- Useful variables -----------------------------
uint8_fillval: &uint8_fillval 255
real_fillval: &real_fillval -1.0e+31
max_float: &max_float 3.4028235e+38
species_valid_max: &species_valid_max 1e20

# ------------------------------- Coordinates -------------------------------
epoch:
  DELTA_MINUS_VAR: epoch_delta_minus
  DELTA_PLUS_VAR: epoch_delta_plus

elevation_angle:
  CATDESC: Elevation Angle
  FIELDNAM: Elevation Angle
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Elevation Angle
  SCALETYP: linear
  UNITS: degrees
  VALIDMAX: 180.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

spin_sector:
  CATDESC: Spin Sector Index
  FIELDNAM: Spin Sector Index
  FILLVAL: *uint8_fillval
  FORMAT: I3
  LABLAXIS: " "
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 12
  VALIDMIN: 0
  VAR_TYPE: support_data

# ------------------------------- labels -------------------------------
elevation_angle_label:
  CATDESC: Elevation Angle
  FIELDNAM: Elevation Angle
  FORMAT: A6
  VAR_TYPE: metadata

# ------------------------------- species -------------------------------
# lo species attrs
lo-species-attrs:
    CATDESC: "{species} Non-sunward Species"
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "Non-sunward - {species}"
    FILLVAL: *real_fillval
    FORMAT: F32.1
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    SCALETYP: log
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: *species_valid_max
    VALIDMIN: 0.0
    VAR_TYPE: data

lo-pui-species-attrs:
    CATDESC: "{species} Pickup Ion Sunward Species"
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "Sunward - {species}"
    FILLVAL: *real_fillval
    FORMAT: F32.1
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    SCALETYP: log
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: *species_valid_max
    VALIDMIN: 0.0
    VAR_TYPE: data

lo-sw-species-attrs:
  CATDESC: "{species} Solar Wind Sunward Species"
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_sector
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: spectrogram
  FIELDNAM: "Sunward - {species}"
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_sector_label
  SCALETYP: log
  UNITS: "#/(cm^2-s-sr-keV/q)"
  VALIDMAX: *species_valid_max
  VALIDMIN: 0.0
  VAR_TYPE: data

lo-species-unc-attrs:
    CATDESC: "{species} Non-sunward Species uncertainty"
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Uncertainty
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "Non-sunward - {species}"
    FILLVAL: *real_fillval
    FORMAT: F32.1
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    SCALETYP: log
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: *species_valid_max
    VALIDMIN: 0.0
    VAR_TYPE: data

lo-pui-species-unc-attrs:
    CATDESC: "{species} Pickup Ion Sunward Species uncertainty"
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Uncertainty
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "Sunward - {species}"
    FILLVAL: *real_fillval
    FORMAT: F32.1
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    SCALETYP: log
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: *species_valid_max
    VALIDMIN: 0.0
    VAR_TYPE: data

lo-sw-species-unc-attrs:
    CATDESC: "{species} Solar Wind Sunward Species uncertainty"
    DEPEND_0: epoch
    DEPEND_1: esa_step
    DEPEND_2: spin_sector
    DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Uncertainty
    DISPLAY_TYPE: spectrogram
    FIELDNAM: "Sunward - {species}"
    FILLVAL: *real_fillval
    FORMAT: F32.1
    LABL_PTR_1: esa_step_label
    LABL_PTR_2: spin_sector_label
    SCALETYP: log
    UNITS: "#/(cm^2-s-sr-keV/q)"
    VALIDMAX: *species_valid_max
    VALIDMIN: 0.0
    VAR_TYPE: data
