# <=== Label Attributes ===>
# LABL_PTR_i expects VAR_TYPE of metadata with char data type.
default_attrs: &default
  # Assumed values for all variable attrs unless overwritten
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  UNITS: ' '
  VALIDMAX: 9223372036854775807
  VALIDMIN: -9223372036854775808
  VAR_TYPE: data

default_coords: &default_coords
  # Assumed values for all coordinate attrs unless overwritten
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: F2.4  # Float with 4 digits
  UNITS: counts
  VALIDMAX: 9223372036854775807
  VALIDMIN: -9223372036854775808
  VAR_TYPE: support_data

mag_support_attrs: &support_default
    <<: *default
    DICT_KEY: SPASE>Support>SupportQuantity:Other
    VAR_TYPE: support_data

mag_metadata_attrs: &metadata_default
    <<: *default
    VAR_TYPE: metadata

direction_label:
  CATDESC: magnetic field vector data
  FIELDNAM: Magnetic Field Vector
  FORMAT: A3
  VAR_TYPE: metadata

compression_label:
  CATDESC: Compression and width
  FIELDNAM: Compression and width
  FORMAT: A2
  VAR_TYPE: metadata

vector_attrs: &vectors_default
    <<: *default
    CATDESC: Magnetic field vectors with x y z varying by time
    CDF_DATA_TYPE: CDF_FLOAT
    DEPEND_1: direction
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:DSRF,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field Vector
    FILLVAL: -1.0e31
    FORMAT: F13.5
    LABL_PTR_1: direction_label
    UNITS: nT
    VALIDMAX: 1.0e+5
    VALIDMIN: -1.0e+5

# Frame-specific vector attributes
vector_attrs_srf:
    <<: *vectors_default
    CATDESC: Magnetic field in the Spacecraft Reference Frame (SRF)
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:SRF,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field SRF

vector_attrs_dsrf:
    <<: *vectors_default
    CATDESC: Magnetic field in the Despun Spacecraft Reference Frame (DSRF)
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:DSRF,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field DSRF

vector_attrs_gse:
    <<: *vectors_default
    CATDESC: Magnetic field in GSE coordinates
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:GSE,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field GSE

vector_attrs_gsm:
    <<: *vectors_default
    CATDESC: Magnetic field in GSM coordinates
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:GSM,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field GSM

vector_attrs_rtn:
    <<: *vectors_default
    CATDESC: Magnetic field in RTN coordinates
    DICT_KEY: "SPASE>Field>FieldQuantity:Magnetic,Qualifier:Vector,CoordinateSystemName:RTN,CoordinateRepresentation:Cartesian"
    FIELDNAM: Magnetic Field RTN

direction_attrs:
    <<: *default_coords
    CATDESC: Magnetic field vector
    DICT_KEY: SPASE>Support>SupportQuantity:Orientation
    DISPLAY_TYPE: time_series
    FIELDNAM: \[xyz\] magnetic field vector
    FORMAT: I3
    LABLAXIS: Magnetic field vector
    VAR_TYPE: support_data


magnitude:
  <<: *support_default
  CATDESC: Magnitude of the magnetic field
  CDF_DATA_TYPE: CDF_FLOAT
  DICT_KEY: SPASE>Field>FieldQuantity:Magnetic,Qualifier:Scalar
  FIELDNAM: Magnetic Field Magnitude
  FILLVAL: -1.0e+31
  FORMAT: F12.5
  LABLAXIS: "|B|"
  UNITS: nT
  VALIDMAX: 1.0e+5
  VALIDMIN: 0
  VAR_TYPE: data

range:
  <<: *support_default
  CATDESC: Range of the magnetometer sensor
  CDF_DATA_TYPE: CDF_UINT1
  DICT_KEY: SPASE>Support>SupportQuantity:InstrumentMode
  FIELDNAM: Sensor Range
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: Range
  UNITS: ' '
  VALIDMAX: 3
  VALIDMIN: 0

pri_sens:
    <<: *support_default
    CATDESC: Indicates the primary sensor. 0 is MAGo, 1 is MAGi
    DICT_KEY: SPASE>Support>SupportQuantity:InstrumentMode
    FIELDNAM: Primary Sensor
    FILLVAL: 255
    FORMAT: I1
    LABLAXIS: Primary Sensor
    UNITS: ' '
    VALIDMAX: 1
    VALIDMIN: 0


qf_bitmask:
  <<: *support_default
  CATDESC: Bitmask indicating when spacecraft related activities influenced the measurement.
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Quality Bitmask
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: QB
  VALIDMAX: 255
  VALIDMIN: 0
  VAR_NOTES: |
    The bitmask is an 8-bit integer where each bit represents a different quality flag.
    The bits are defined as follows:
    - Bit 0: Data is sourced from secondary sensor
    - Bit 1: Thruster firing signals have been removed
    - Bit 2: Spacecraft interference impacts this data
    - Bit 3: Instrument signals have been removed
    - Bits 4-7: Reserved for in flight calibration

qf:
  <<: *support_default
  CATDESC: "Data quality flag. 0: Good data, 1: Bad data."
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  FIELDNAM: Quality Flag
  FILLVAL: 255
  FORMAT: I1
  LABLAXIS: QF
  UNITS: 0=good
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_NOTES: |
    The quality flag indicates the overall quality of the data at each timestamp.
    More detail on the data quality can be found in the quality bitmask.
    - 0: Good data
    - 1: Bad quality data not suitable for science
  VAR_TYPE: data
