Descriptor: MAG>Magnetometer
TEXT: >
  The IMAP magnetometer (MAG) consists of a pair of identical magnetometers
  which each measure the magnetic field in three directions in the vicinity of
  the spacecraft.
  MAG will contribute to our understanding of the acceleration and transport
  of charged particles in the heliosphere.
  MAG design and assembly is led by Imperial College, London. See
  https://imap.princeton.edu/instruments/mag for more details.

imap_mag_l1a_burst-raw:
  Data_type: L1A_raw-burst>Level-1A raw burst rate
  Logical_source: imap_mag_l1a_burst-raw
  Logical_source_description: IMAP Mission MAG Burst Rate Instrument Level-1A Data.

