# TODO: add attributes for science packets
# TODO: update label_axis and min/max with values provided by instrument team.

# <=== Defaults ===>
# Assumed values for all variable attrs unless overwritten
default_attrs: &default
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  VALIDMIN: 0
  VALIDMAX: 9223372036854775807
  VAR_TYPE: data
  UNITS: ' '
  SCALETYP: linear

hk_support_attrs: &support_default
  <<: *default
  DISPLAY_TYPE: no_plot
  VAR_TYPE: ignore_data

# <=== Coordinates ===>
epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  FILLVAL: -9223372036854775808
  FORMAT: " " # Supposedly not required, fails in xarray_to_cdf
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid

adc_channels:   # adc_channels is a dependency for leak_i data variable
  DISPLAY_TYPE: no_plot
  FILLVAL: -9223372036854775808
  UNITS: ' '
  SCALETYP: linear
  VALIDMIN: 0
  VALIDMAX: 63
  VAR_TYPE: metadata
  CATDESC: ADC Channel
  FIELDNAM: ADC Channel
  LABLAXIS: Channel
  FORMAT: I2


# <=== Data Variable Attributes ===>
#TODO is DEPEND_0 needed for no_plot variables in housekeeping?

fsw_version_a:
  <<: *support_default
  VALIDMAX: 3
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number A
  LABLAXIS: FSW A
  FORMAT: I1

fsw_version_b:
  <<: *support_default
  VALIDMAX: 15
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number B
  LABLAXIS: FSW B
  FORMAT: I2

fsw_version_c:
  <<: *support_default
  VALIDMAX: 63
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number C
  LABLAXIS: FSW C
  FORMAT: I2

num_good_cmds:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Number of Good Commands
  FIELDNAM: Number of Good Commands
  LABLAXIS: Counts
  FORMAT: I3

last_good_cmd:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Last Good Command
  FIELDNAM: Last Good Command
  LABLAXIS: Last cmd
  FORMAT: I3

last_good_seq_num:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Last Good Sequence Number
  FIELDNAM: Last Good Sequence Number
  LABLAXIS: Last num
  FORMAT: I3

num_bad_cmds:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Number of Bad Commands
  FIELDNAM: Number of Bad Commands
  LABLAXIS: Counts
  FORMAT: I3

last_bad_cmd:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Last Bad Command
  FIELDNAM: Last Bad Command
  LABLAXIS: Last cmd
  FORMAT: I3

last_bad_seq_num:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Last Bad Sequence Number
  FIELDNAM: Last Bad Sequence Number
  LABLAXIS: Last num
  FORMAT: I3

fee_running:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - FEE Running (1) or Reset (0)
  FIELDNAM: FEE Running (1) or Reset (0)
  LABLAXIS: State
  FORMAT: I1

mram_disabled:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - MRAM Disabled (1) or Enabled (0)
  FIELDNAM: MRAM Disabled (1) or Enabled (0)
  LABLAXIS: State
  FORMAT: I1

enable_50khz:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - 50kHz Enabled (1) or Disabled (0)
  FIELDNAM: 50kHz Enabled (1) or Disabled (0)
  LABLAXIS: State
  FORMAT: I1

enable_hvps:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - HVPS Enabled (1) or Disabled (0)
  FIELDNAM: HVPS Enabled (1) or Disabled (0)
  LABLAXIS: State
  FORMAT: I1

table_status:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - Table Status OK (1) or Error (0)
  FIELDNAM: Table Status OK (1) or Error (0)
  LABLAXIS: Status
  FORMAT: I1

heater_control:
  <<: *support_default
  VALIDMAX: 2
  CATDESC: State - Heater Control (0=None, 1=Pri, 2=Sec)
  FIELDNAM: Heater Control (0=None, 1=Pri, 2=Sec)
  LABLAXIS: State
  FORMAT: I1

adc_mode:
  <<: *support_default
  VALIDMAX: 3
  CATDESC: State - ADC Mode (0=quiet, 1=normal, 2=adcstim, 3=adcThreshold
  FIELDNAM: ADC Mode (0=quiet, 1=normal, 2=adcstim, 3=adcThreshold)
  LABLAXIS: ADC mode
  FORMAT: I1

mode:
  <<: *support_default
  VALIDMAX: 3
  CATDESC: State - Mode (0=Boot, 1=Maintenance, 2=Standby, 3=Science)
  FIELDNAM: Mode (0=Boot, 1=Maintenance, 2=Standby, 3=Science)
  LABLAXIS: Mode
  FORMAT: I1

dyn_thresh_lvl:
  <<: *support_default
  VALIDMAX: 3
  CATDESC: Dynamic Threshold Level (0-3)
  FIELDNAM: Dynamic Threshold Level (0-3)
  LABLAXIS: Level
  FORMAT: I1

num_evnt_last_hk:
  <<: *support_default
  VALIDMAX: 262143
  CATDESC: Number of Events Since Last HK Update
  FIELDNAM: Number of Events Since Last HK Update
  LABLAXIS: Num events
  FORMAT: I6

num_errors:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: Number of Errors
  FIELDNAM: Number of Errors
  LABLAXIS: Num errors
  FORMAT: I3

last_error_num:
  <<: *support_default
  VALIDMAX: 255
  CATDESC: State - Last Error Number
  FIELDNAM: Last Error Number
  LABLAXIS: Error num
  FORMAT: I3

code_checksum:
  <<: *support_default
  VALIDMAX: 65535
  CATDESC: Code Checksum
  FIELDNAM: Code Checksum
  LABLAXIS: Checksum
  FORMAT: I5

spin_period_short:
  <<: *support_default
  VALIDMAX: 65535
  CATDESC: Spin Period Short at T=0
  FIELDNAM: Spin Period Short at T=0
  LABLAXIS: Spin period short
  FORMAT: I5

spin_period_long:
  <<: *support_default
  VALIDMAX: 65535
  CATDESC: Spin Period Long at T=0
  FIELDNAM: Spin Period Long at T=0
  LABLAXIS: Spin period long
  FORMAT: I5

leak_i:
  <<: *support_default
  DEPEND_1: adc_channels
  CATDESC: Leakage Current [I]
  FIELDNAM: Leakage Current [I]
  LABLAXIS: Current I
  labl_ptr: adc_channels
  FORMAT: I19

phasic_stat:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - Phasic Status
  FIELDNAM: Phasic Status
  LABLAXIS: Status
  FORMAT: I1

active_heater:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - Active Heater
  FIELDNAM: Active Heater
  LABLAXIS: State
  FORMAT: I1

heater_on:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - Heater On/Off
  FIELDNAM: Heater On/Off
  LABLAXIS: State
  FORMAT: I1

test_pulser_on:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - Test Pulser On/Off
  FIELDNAM: Test Pulser On/Off
  LABLAXIS: State
  FORMAT: I1

dac0_enable:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - DAC 0 Enable
  FIELDNAM: DAC 0 Enable
  LABLAXIS: State
  FORMAT: I1

dac1_enable:
  <<: *support_default
  VALIDMAX: 1
  CATDESC: State - DAC 1 Enable
  FIELDNAM: DAC 1 Enable
  LABLAXIS: State
  FORMAT: I1


# TODO Update data formats. Should be float values. Need more info from instrument team

preamp_l234a:
  <<: *default
  VALIDMAX: 4095  # Need more info from instr. team
  CATDESC: Preamp L234A Voltage
  FIELDNAM: Preamp L234A Voltage
  LABLAXIS: Voltage
  FORMAT: I4
  UNITS: V
  FILLVAL: -1.0000000E+31

preamp_l1a:
  <<: *default
  VALIDMAX: 4095  # Need more info from instr. team
  CATDESC: Preamp L1A Voltage
  FIELDNAM: Preamp L1A Voltage
  LABLAXIS: Voltage
  FORMAT: I4
  UNITS: V
  FILLVAL: -1.0000000E+31

preamp_l1b:
  <<: *default
  VALIDMAX: 4095  # Need more info from instr. team
  CATDESC: Preamp L1B Voltage
  FIELDNAM: Preamp L1B Voltage
  LABLAXIS: Voltage
  FORMAT: I4
  UNITS: V
  FILLVAL: -1.0000000E+31

preamp_l234b:
  <<: *default
  VALIDMAX: 4095 # Need more info from instr. team
  CATDESC: Preamp L234B Voltage
  FIELDNAM: Preamp L234B Voltage
  LABLAXIS: Voltage
  FORMAT: I2
  UNITS: V
  FILLVAL: -1.0000000E+31

temp0:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 57
  CATDESC: FEE LDO Regulator Mounted on the Board Next to the Low-dropout Regulator
  FIELDNAM: FEE LDO Regulator
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

temp1:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 50
  CATDESC: Primary Heater Mounted on the Board Next to the Primary Heater Circuit
  FIELDNAM: Primary Heater
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

temp2:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 50
  CATDESC: FEE FPGA Mounted on the Board Next to the FPGA
  FIELDNAM: FEE FPGA
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

temp3:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 50
  CATDESC: Secondary Heater
  FIELDNAM: Secondary Heater
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

analog_temp:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 50
  CATDESC: Chassis Temp Mounted on the Analog Board Close to Thermostats, Heaters, and Chassis
  FIELDNAM: Analog Temp
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

hvps_temp:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 50
  CATDESC: Board Temp Mounted Inside Faraday Cage in Middle of Board Near Connector Side
  FIELDNAM: Board Temp
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

idpu_temp:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 65
  CATDESC: LDO Temp Mounted on Top of the Low-dropout Regulator
  FIELDNAM: LDO Temp
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

lvps_temp:
  <<: *default
  VALIDMIN: -25
  VALIDMAX: 80
  CATDESC: Board Temp Mounted in the Middle of Board on Opposite Side of Hottest Component
  FIELDNAM: Board Temp
  LABLAXIS: Temperature
  FORMAT: I2
  UNITS: C
  FILLVAL: -1.0000000E+31

ebox_3d4vd:
  <<: *default
  # doc says min 3.1
  # doc says max 3.6
  VALIDMIN: 3
  VALIDMAX: 4
  CATDESC: 3.4VD Ebox (Digital)
  FIELDNAM: 3.4VD Ebox (Digital)
  LABLAXIS: Voltage
  FORMAT: F2.1
  UNITS: V
  FILLVAL: -1.0000000E+31

ebox_5d1vd:
  <<: *default
  # doc says min 4.85
  # doc says max 5.45
  VALIDMIN: 4
  VALIDMAX: 6
  CATDESC: 5.1VD Ebox (Digital)
  FIELDNAM: 5.1VD Ebox (Digital)
  LABLAXIS: Voltage
  FORMAT: F3.2
  UNITS: V
  FILLVAL: -1.0000000E+31

ebox_p12va:
  <<: *default
  # doc says min 11.2
  # doc says max 13.1
  VALIDMIN: 11
  VALIDMAX: 14
  CATDESC: +12VA Ebox (Analog)
  FIELDNAM: +12VA Ebox (Analog)
  LABLAXIS: Voltage
  FORMAT: F3.1
  UNITS: V
  FILLVAL: -1.0000000E+31

ebox_m12va:
  <<: *default
  # doc says min -13.1
  # doc says max -11.2
  VALIDMIN: -14
  VALIDMAX: -12
  CATDESC: -12VA Ebox (Analog)
  FIELDNAM: -12VA Ebox (Analog)
  LABLAXIS: Voltage
  FORMAT: F3.1
  UNITS: V
  FILLVAL: -1.0000000E+31

ebox_p5d7va:
  <<: *default
  # doc says min 5.3
  # doc says max 6.3
  VALIDMIN: 5
  VALIDMAX: 7
  CATDESC: +5.7VA Ebox (Analog)
  FIELDNAM: +5.7VA Ebox (Analog)
  LABLAXIS: Voltage
  FORMAT: F2.1
  UNITS: V
  FILLVAL: -1.0000000E+31

ebox_m5d7va:
  <<: *default
  # doc says min -6.4125
  # doc says max -5.25
  VALIDMIN: -7
  VALIDMAX: -5
  CATDESC: -5.7VA Ebox (Analog)
  FIELDNAM: -5.7VA Ebox (Analog)
  LABLAXIS: Voltage
  FORMAT: F5.4
  UNITS: V
  FILLVAL: -1.0000000E+31

ref_p5v:
  #Need more info from instrument team on min and max values
  <<: *default
  CATDESC: +5V ref
  FIELDNAM: +5V ref
  LABLAXIS: Voltage
  FORMAT: I4
  UNITS: V
  FILLVAL: -1.0000000E+31

l1ab_bias:
  <<: *default
  VALIDMIN: 0
  VALIDMAX: 15
  CATDESC: L1A/B Bias
  FIELDNAM: L1A/B Bias
  LABLAXIS: Voltage
  FORMAT: I2
  UNITS: V
  FILLVAL: -1.0000000E+31

l2ab_bias:
  <<: *default
  VALIDMIN: 0
  VALIDMAX: 25
  CATDESC: L2A/B Bias
  FIELDNAM: L2A/B Bias
  LABLAXIS: Voltage
  FORMAT: I2
  UNITS: V
  FILLVAL: -1.0000000E+31

l34a_bias:
  <<: *default
  VALIDMIN: 0
  VALIDMAX: 255
  CATDESC: L3/4A Bias
  FIELDNAM: L3/4A Bias
  LABLAXIS: Voltage
  FORMAT: I3
  UNITS: V
  FILLVAL: -1.0000000E+31

l34b_bias:
  <<: *default
  VALIDMIN: 0
  VALIDMAX: 225
  CATDESC: L3/4B Bias
  FIELDNAM: L3/4B Bias
  LABLAXIS: Voltage
  FORMAT: I3
  UNITS: V
  FILLVAL: -1.0000000E+31

ebox_p2d0vd:
  <<: *default
  # doc says min 1.79
  # doc says max 2.5
  VALIDMIN: 1
  VALIDMAX: 3
  CATDESC: +2.0VD Ebox (Digital)
  FIELDNAM: +2.0VD Ebox (Digital)
  LABLAXIS: Voltage
  FORMAT: F3.2
  UNITS: V
  FILLVAL: -1.0000000E+31

