# ----------------------------- Useful variables -----------------------------
uint8_fillval: &uint8_fillval 255
uint32_fillval: &uint32_fillval 4294967295
real_fillval: &real_fillval -1.0e+31

min_int: &min_int -9223372036854775808
max_int: &max_int 9223372036854775807

# --------------------------- Default attributes -----------------------------
energy_attrs: &energy_default
  CATDESC: Geometric mean energy per nucleon
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Characteristic
  DISPLAY_TYPE: time_series
  FIELDNAM: Energy Table
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABLAXIS: Energy
  SCALETYP: log
  UNITS: MeV/nuc
  VALIDMAX: 200.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

# ------------------------------- Coordinates -------------------------------
epoch_delta_minus:
  CATDESC: Time from acquisition start to acquisition center
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal,Qualifier:Uncertainty
  FIELDNAM: epoch delta minus
  FILLVAL: *min_int
  FORMAT: I19
  LABLAXIS: Epoch Delta Minus
  SCALETYP: linear
  UNITS: ns
  VALIDMAX: *max_int
  VALIDMIN: *min_int
  VAR_TYPE: support_data

epoch_delta_plus:
  CATDESC: Time from acquisition center to acquisition end
  DICT_KEY: SPASE>Support>SupportQuantity:Temporal,Qualifier:Uncertainty
  FIELDNAM: epoch delta plus
  FILLVAL: *min_int
  FORMAT: I19
  LABLAXIS: Epoch Delta Plus
  SCALETYP: linear
  UNITS: ns
  VALIDMAX: *max_int
  VALIDMIN: *min_int
  VAR_TYPE: support_data

energy_cno:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_cno_minus
  DELTA_PLUS_VAR: energy_cno_plus

energy_fe:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_fe_minus
  DELTA_PLUS_VAR: energy_fe_plus

energy_h:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_h_minus
  DELTA_PLUS_VAR: energy_h_plus

energy_he3he4:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_he3he4_minus
  DELTA_PLUS_VAR: energy_he3he4_plus

energy_c:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_c_minus
  DELTA_PLUS_VAR: energy_c_plus

energy_he3:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_he3_minus
  DELTA_PLUS_VAR: energy_he3_plus

energy_he4:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_he4_minus
  DELTA_PLUS_VAR: energy_he4_plus

energy_junk:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_junk_minus
  DELTA_PLUS_VAR: energy_junk_plus

energy_ne_mg_si:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_ne_mg_si_minus
  DELTA_PLUS_VAR: energy_ne_mg_si_plus

energy_o:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_o_minus
  DELTA_PLUS_VAR: energy_o_plus

energy_uh:
  <<: *energy_default
  DELTA_MINUS_VAR: energy_uh_minus
  DELTA_PLUS_VAR: energy_uh_plus

# ------------------------------- Label vars --------------------------------
epoch_delta_minus_label:
  CATDESC: Time from acquisition start to acquisition center
  FIELDNAM: Epoch delta minus
  FORMAT: A18
  VAR_TYPE: metadata

epoch_delta_plus_label:
  CATDESC: Time from acquisition center to acquisition end
  FIELDNAM: Epoch delta plus
  FORMAT: A18
  VAR_TYPE: metadata

# ------------------------------- Labels ------------------------------------
energy_cno_label:
  CATDESC: Energy CNO
  FIELDNAM: Energy CNO
  FORMAT: A6
  VAR_TYPE: metadata

energy_fe_label:
  CATDESC: Energy Fe
  FIELDNAM: Energy Fe
  FORMAT: A6
  VAR_TYPE: metadata

energy_h_label:
  CATDESC: Energy H
  FIELDNAM: Energy H
  FORMAT: A6
  VAR_TYPE: metadata

energy_he3he4_label:
  CATDESC: Energy He3He4
  FIELDNAM: Energy He3He4
  FORMAT: A6
  VAR_TYPE: metadata

energy_c_label:
  CATDESC: Energy C
  FIELDNAM: Energy C
  FORMAT: A6
  VAR_TYPE: metadata

energy_he3_label:
  CATDESC: Energy He3
  FIELDNAM: Energy He3
  FORMAT: A6
  VAR_TYPE: metadata

energy_he4_label:
  CATDESC: Energy He4
  FIELDNAM: Energy He4
  FORMAT: A6
  VAR_TYPE: metadata

energy_junk_label:
  CATDESC: Energy Junk
  FIELDNAM: Energy Junk
  FORMAT: A6
  VAR_TYPE: metadata

energy_ne_mg_si_label:
  CATDESC: Energy NeMgSi
  FIELDNAM: Energy NeMgSi
  FORMAT: A6
  VAR_TYPE: metadata

energy_o_label:
  CATDESC: Energy O
  FIELDNAM: Energy O
  FORMAT: A6
  VAR_TYPE: metadata

energy_uh_label:
  CATDESC: Energy UH
  FIELDNAM: Energy UH
  FORMAT: A6
  VAR_TYPE: metadata

# --------------------------- Dataset variable attrs ------------------------
# The following are set in multiple data products
data_quality:
  CATDESC: Indicates whether data quality is suspect (1).
  DEPEND_0: epoch
  DICT_KEY: SPASE>Support>SupportQuantity:DataQuality
  DISPLAY_TYPE: time_series
  FIELDNAM: Data Quality
  FILLVAL: *uint8_fillval
  FORMAT: '%d'
  LABLAXIS: Data Quality
  SCALETYP: linear
  UNITS: ' '
  VALIDMAX: 1
  VALIDMIN: 0
  VAR_TYPE: data
  VAR_TYPE: support_data

# ----- hi-omni Attributes -----
# Species plus and minus attrs:
energy_c_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_c
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_c_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_c
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_fe_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_fe_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_h_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_h_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_he3_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_he3
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_he3_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_he3
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_he4_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_he4_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_junk_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_junk
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_junk_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_junk
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_ne_mg_si_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_ne_mg_si
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_ne_mg_si_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_ne_mg_si
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_o_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_o
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_o_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_o
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

energy_uh_minus:
  <<: *energy_default
  CATDESC: Energy Table Minus value
  DEPEND_1: energy_uh
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta minus

energy_uh_plus:
  <<: *energy_default
  CATDESC: Energy Table Plus value
  DEPEND_1: energy_uh
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:EnergyPerCharge,Qualifier:Uncertainty
  FIELDNAM: energy delta plus

# Uncertainty attrs:
unc_c:
  CATDESC: Uncertainties for c (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_c
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for c
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_c_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_fe:
  CATDESC: Uncertainties for fe (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_fe
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for fe
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_fe_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_h:
  CATDESC: Uncertainties for h (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_h
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for h
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_h_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_he3:
  CATDESC: Uncertainties for he3 (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_he3
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for he3
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he3_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_he4:
  CATDESC: Uncertainties for he4 (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_he4
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for he4
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he4_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_junk:
  CATDESC: Uncertainties for junk (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_junk
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for junk
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_junk_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_ne_mg_si:
  CATDESC: Uncertainties for ne-mg-si (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_ne_mg_si
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for ne-mg-si
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_ne_mg_si_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_o:
  CATDESC: Uncertainties for o (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_o
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for o
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_o_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data

unc_uh:
  CATDESC: Uncertainties for uh (Root 2 spacing)
  COORDINATE_SYSTEM: instrument frame
  DEPEND_0: epoch
  DEPEND_1: energy_uh
  DISPLAY_TYPE: time_series
  FIELDNAM: Uncertainties for uh
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_uh_label
  SCALETYP: log
  SI_CONVERSION: ' > '
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 4096.0
  VALIDMIN: 0.0
  VAR_TYPE: support_data
c:
  CATDESC: c (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_c
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - c
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_c_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

fe:
  CATDESC: fe (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_fe
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - fe
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_fe_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

h:
  CATDESC: h (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_h
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - h
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_h_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

he3:
  CATDESC: he3 (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_he3
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - he3
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he3_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

he4:
  CATDESC: he4 (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_he4
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - he4
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_he4_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

junk:
  CATDESC: junk (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_junk
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - junk
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_junk_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

ne_mg_si:
  CATDESC: ne-mg-si (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_ne_mg_si
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - ne-mg-si
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_ne_mg_si_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

o:
  CATDESC: o (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_o
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - o
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_o_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data

uh:
  CATDESC: uh (Root 2 spacing)
  DEPEND_0: epoch
  DEPEND_1: energy_uh
  DICT_KEY: SPASE>Particle>ParticleType:Ion,ParticleQuantity:NumberFlux,Qualifier:Differential
  DISPLAY_TYPE: time_series
  FIELDNAM: Diff. Intensity - uh
  FILLVAL: *real_fillval
  FORMAT: F32.1
  LABL_PTR_1: energy_uh_label
  SCALETYP: log
  UNITS: '# / cm2 s sr MeV/nuc'
  VALIDMAX: 16777216.0
  VALIDMIN: 0.0
  VAR_TYPE: data
