codecov:
 token: 0d68c117-71d9-44f4-bcc9-fbf4e37aa897
coverage:
  status:
    patch:
      default:
        target: 90%
        paths:
          - imap_processing/**/*.py
    project:
      default:
        target: 90%
        paths:
          - imap_processing/**/*.py