import dataclasses
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pytest
import xarray as xr

from imap_processing.cdf.imap_cdf_manager import ImapCdfAttributes
from imap_processing.cdf.utils import write_cdf
from imap_processing.glows.l1b.glows_l1b import (
    glows_l1b,
    glows_l1b_de,
    process_de,
    process_histogram,
)
from imap_processing.glows.l1b.glows_l1b_data import (
    AncillaryParameters,
    DirectEventL1B,
    HistogramL1B,
    PipelineSettings,
)
from imap_processing.spice.time import met_to_datetime64
from imap_processing.tests.glows.conftest import mock_update_spice_parameters


# Fixture for L1a histogram dataset
@pytest.fixture
def hist_dataset():
    variables = {
        "seq_count_in_pkts_file": np.zeros((20,)),
        "first_spin_id": np.zeros((20,)),
        "last_spin_id": np.zeros((20,)),
        "flags_set_onboard": np.zeros((20,)),
        "is_generated_on_ground": np.zeros((20,)),
        "number_of_spins_per_block": np.zeros((20,)),
        "number_of_bins_per_histogram": np.full((20,), 3600),
        "number_of_events": np.zeros((20,)),
        "filter_temperature_average": np.zeros((20,)),
        "filter_temperature_variance": np.zeros((20,)),
        "hv_voltage_average": np.zeros((20,)),
        "hv_voltage_variance": np.zeros((20,)),
        "spin_period_average": np.zeros((20,)),
        "spin_period_variance": np.zeros((20,)),
        "pulse_length_average": np.zeros((20,)),
        "pulse_length_variance": np.zeros((20,)),
        "imap_start_time": np.zeros((20,)),
        "imap_time_offset": np.zeros((20,)),
        "glows_start_time": np.zeros((20,)),
        "glows_time_offset": np.zeros((20,)),
    }
    cdf_attrs = ImapCdfAttributes()
    cdf_attrs.add_instrument_global_attrs("glows")
    cdf_attrs.add_instrument_variable_attrs("glows", "l1a")

    epoch = xr.DataArray(
        np.arange(20),
        name="epoch",
        dims=["epoch"],
        attrs=cdf_attrs.get_variable_attributes("epoch", check_schema=False),
    )

    bins = xr.DataArray(np.arange(3600), name="bins", dims=["bins"])

    ds = xr.Dataset(
        attrs=cdf_attrs.get_global_attributes("imap_glows_l1a_hist"),
    )

    ds["histogram"] = xr.DataArray(
        np.zeros((20, 3600)),
        dims=["epoch", "bins"],
        coords={"epoch": epoch, "bins": bins},
    )

    for var, data in variables.items():
        ds[var] = xr.DataArray(data, dims=["epoch"], coords={"epoch": epoch})

    ds.attrs["flight_software_version"] = np.array([67], dtype=int)
    ds.attrs["Parents"] = ["test_packet_file.pkts", "test_spice_file.tls"]

    return ds


@pytest.fixture
def de_dataset():
    variables = {
        "seq_count_in_pkts_file": np.zeros((20,)),
        "number_of_de_packets": np.zeros((20,)),
        "imap_sclk_last_pps": np.zeros((20,)),
        "glows_sclk_last_pps": np.zeros((20,)),
        "glows_ssclk_last_pps": np.zeros((20,)),
        "imap_sclk_next_pps": np.zeros((20,)),
        "catbed_heater_active": np.zeros((20,)),
        "spin_period_valid": np.zeros((20,)),
        "spin_phase_at_next_pps_valid": np.zeros((20,)),
        "spin_period_source": np.zeros((20,)),
        "spin_period": np.zeros((20,)),
        "spin_phase_at_next_pps": np.zeros((20,)),
        "number_of_completed_spins": np.zeros((20,)),
        "filter_temperature": np.zeros((20,)),
        "hv_voltage": np.zeros((20,)),
        "glows_time_on_pps_valid": np.zeros((20,)),
        "time_status_valid": np.zeros((20,)),
        "housekeeping_valid": np.zeros((20,)),
        "is_pps_autogenerated": np.zeros((20,)),
        "hv_test_in_progress": np.zeros((20,)),
        "pulse_test_in_progress": np.zeros((20,)),
        "memory_error_detected": np.zeros((20,)),
    }

    cdf_attrs = ImapCdfAttributes()
    cdf_attrs.add_instrument_global_attrs("glows")
    cdf_attrs.add_instrument_variable_attrs("glows", "l1b")

    epoch = xr.DataArray(
        np.arange(20),
        name="epoch",
        dims=["epoch"],
        attrs=cdf_attrs.get_variable_attributes("epoch"),
    )

    within_the_second = xr.DataArray(
        np.arange(2295), name="within_the_second", dims=["within_the_second"]
    )
    direct_event = xr.DataArray(
        np.arange(4), name="direct_event_components", dims=["direct_event_components"]
    )

    de_data = np.zeros((20, 2295, 4))
    de_data[0][0] = [1, 2_000, 3, 0]

    variables["filter_temperature"][0] = 100

    ds = xr.Dataset(
        coords={
            "epoch": epoch,
            "within_the_second": within_the_second,
            "direct_event_components": direct_event,
        },
        attrs=cdf_attrs.get_global_attributes("imap_glows_l1b_de"),
    )

    ds["direct_events"] = xr.DataArray(
        de_data,
        dims=["epoch", "within_the_second", "direct_event_components"],
        coords={
            "epoch": epoch,
            "within_the_second": within_the_second,
            "direct_event_components": direct_event,
        },
    )

    ds.attrs["Parents"] = ["test_packet_file.pkts", "test_spice_file.tls"]

    for var, data in variables.items():
        ds[var] = xr.DataArray(data, dims=["epoch"], coords={"epoch": epoch})

    return ds


@pytest.fixture
def ancillary_dict():
    dictionary = {
        "description": "Table for conversion/decoding ancillary parameters collected "
        "onboard by IMAP/GLOWS",
        "version": "0.1",
        "date_of_creation_yyyymmdd": "20230527",
        "filter_temperature": {
            "min": -30.0,
            "max": 80.0,
            "n_bits": 8,
            "p01": 0.0,
            "p02": 0.0,
            "p03": 0.0,
            "p04": 0.0,
        },
        "hv_voltage": {
            "min": 0.0,
            "max": 3500.0,
            "n_bits": 12,
            "p01": 0.0,
            "p02": 0.0,
            "p03": 0.0,
            "p04": 0.0,
        },
        "spin_period": {"min": 0.0, "max": 20.9712, "n_bits": 16},
        "spin_phase": {"min": 0.0, "max": 360.0, "n_bits": 16},
        "pulse_length": {
            "min": 0.0,
            "max": 255.0,
            "n_bits": 8,
            "p01": 0.0,
            "p02": 0.0,
            "p03": 0.0,
            "p04": 0.0,
        },
    }
    return dictionary


@patch.object(
    HistogramL1B,
    "flag_uv_and_excluded",
    return_value=(np.zeros(3600, dtype=bool), np.zeros(3600, dtype=bool)),
)
@patch.object(HistogramL1B, "update_spice_parameters", autospec=True)
def test_histogram_mapping(
    mock_spice_function,
    mock_flag_uv_and_excluded,
    mock_ancillary_exclusions,
    mock_ancillary_parameters,
    mock_pipeline_settings,
):
    mock_spice_function.side_effect = mock_update_spice_parameters
    time_val = np.double(1111111.11)

    test_hists = np.zeros(3600)
    expected_temp = 100
    encoded_val = np.double(expected_temp * 2.3182 + 69.5455)

    # For now, testing types and number of inputs
    pipeline_settings = PipelineSettings(
        mock_pipeline_settings.sel(
            epoch=mock_pipeline_settings.epoch[0], method="nearest"
        )
    )

    output = tuple(
        dataclasses.asdict(
            HistogramL1B(
                test_hists,
                0,
                0,
                0,
                0,
                0,
                0,
                3600,
                0,
                encoded_val,
                encoded_val,
                encoded_val,
                encoded_val,
                encoded_val,
                encoded_val,
                encoded_val,
                encoded_val,
                time_val,
                time_val,
                time_val,
                time_val,
                mock_ancillary_exclusions,
                mock_ancillary_parameters,
                pipeline_settings,
            )
        ).values()
    )

    # Correctly decoded temperature
    assert np.isclose(output[9], expected_temp, 0.1)

    # Ensure time values are correctly mapped
    assert output[17] == time_val
    assert output[20] == time_val


@patch.object(
    HistogramL1B,
    "flag_uv_and_excluded",
    return_value=(np.zeros(3600, dtype=bool), np.zeros(3600, dtype=bool)),
)
@patch.object(HistogramL1B, "update_spice_parameters", autospec=True)
def test_process_histogram(
    mock_spice_function,
    mock_flag_uv_and_excluded,
    hist_dataset,
    mock_ancillary_exclusions,
    mock_ancillary_parameters,
    mock_pipeline_settings,
):
    mock_spice_function.side_effect = mock_update_spice_parameters

    time_val = np.double(1111111.11)
    expected_temp = 100

    test_hists = np.zeros(3600)
    # For temp
    encoded_val = np.double(expected_temp * 2.3182 + 69.5455)

    pipeline_settings = PipelineSettings(
        mock_pipeline_settings.sel(
            epoch=mock_pipeline_settings.epoch[0], method="nearest"
        )
    )

    test_l1b = HistogramL1B(
        test_hists,
        0,
        0,
        0,
        0,
        0,
        0,
        3600,
        0,
        encoded_val,
        encoded_val,
        encoded_val,
        encoded_val,
        encoded_val,
        encoded_val,
        encoded_val,
        encoded_val,
        time_val,
        time_val,
        time_val,
        time_val,
        mock_ancillary_exclusions,
        mock_ancillary_parameters,
        pipeline_settings,
    )

    output = process_histogram(
        hist_dataset,
        mock_ancillary_exclusions,
        mock_ancillary_parameters,
        pipeline_settings,
    )
    assert len(output) == len(dataclasses.asdict(test_l1b))


@patch.object(
    HistogramL1B,
    "flag_uv_and_excluded",
    return_value=(np.zeros(3600, dtype=bool), np.zeros(3600, dtype=bool)),
)
@patch.object(HistogramL1B, "update_spice_parameters", autospec=True)
def test_bins_from_histogram_not_nbins(
    mock_spice_function,
    mock_flag_uv_and_excluded,
    hist_dataset,
    mock_ancillary_exclusions,
    mock_ancillary_parameters,
    mock_pipeline_settings,
):
    """Output bin arrays should use len(histogram), not number_of_bins_per_histogram."""
    mock_spice_function.side_effect = mock_update_spice_parameters
    # Set NBINS to a value that differs from the actual histogram length (3600)
    hist_dataset["number_of_bins_per_histogram"][:] = 225

    pipeline_settings = PipelineSettings(
        mock_pipeline_settings.sel(
            epoch=mock_pipeline_settings.epoch[0], method="nearest"
        )
    )
    output = process_histogram(
        hist_dataset,
        mock_ancillary_exclusions,
        mock_ancillary_parameters,
        pipeline_settings,
    )
    # All output variables with a bins dimension must use len(histogram), not NBINS
    for da in output:
        if "bins" in da.sizes:
            assert da.sizes["bins"] == 3600


def test_process_de(de_dataset, ancillary_dict, mock_ancillary_parameters):
    output = process_de(de_dataset, mock_ancillary_parameters)

    # Output has the same length as non-initvar fields in DirectEventL1B
    assert len(output) == len(dataclasses.fields(DirectEventL1B))

    # Validate timeestamp
    assert np.isclose(output[-2][0].data[0], 1.001)
    # Validate pulse length
    assert output[-1][0].data[0] == 3.0

    ancillary = AncillaryParameters(ancillary_dict)

    expected_temp = ancillary.decode("filter_temperature", 100.0)

    assert np.isclose(output[8].data[0], expected_temp)


@patch.object(
    HistogramL1B,
    "flag_uv_and_excluded",
    return_value=(np.zeros(3600, dtype=bool), np.zeros(3600, dtype=bool)),
)
@patch.object(HistogramL1B, "update_spice_parameters", autospec=True)
def test_glows_l1b(
    mock_spice_function,
    mock_flag_uv_and_excluded,
    de_dataset,
    hist_dataset,
    mock_ancillary_exclusions,
    mock_pipeline_settings,
    mock_conversion_table_dict,
):
    mock_spice_function.side_effect = mock_update_spice_parameters

    hist_output = glows_l1b(
        hist_dataset,
        mock_ancillary_exclusions.excluded_regions,
        mock_ancillary_exclusions.uv_sources,
        mock_ancillary_exclusions.suspected_transients,
        mock_ancillary_exclusions.exclusions_by_instr_team,
        mock_pipeline_settings,
        mock_conversion_table_dict,
    )

    assert hist_output["histogram"].dims == ("epoch", "bins")
    assert hist_output["histogram"].shape == (20, 3600)

    # This needs to be added eventually, but is skipped for now.
    expected_de_data = [
        "pkts_file_name",
        "ancillary_data_files",
    ]

    # From table 11 in the algorithm document
    expected_hist_data = [
        # "unique_block_identifier", Left out until I determine where to put string data
        "glows_start_time",
        "glows_time_offset",
        "imap_start_time",
        "imap_time_offset",
        "number_of_spins_per_block",
        "number_of_bins_per_histogram",
        "histogram",  # named histogram in alg doc
        "number_of_events",
        "imap_spin_angle_bin_cntr",
        "histogram_flag_array",
        "filter_temperature_average",
        "filter_temperature_std_dev",
        "hv_voltage_average",
        "hv_voltage_std_dev",
        "spin_period_average",
        "spin_period_std_dev",
        "pulse_length_average",
        "pulse_length_std_dev",
        "spin_period_ground_average",
        "spin_period_ground_std_dev",
        "position_angle_offset_average",
        "position_angle_offset_std_dev",
        "spin_axis_orientation_std_dev",
        "spin_axis_orientation_average",
        "spacecraft_location_average",
        "spacecraft_location_std_dev",
        "spacecraft_velocity_average",
        "spacecraft_velocity_std_dev",
        "flags",
    ]
    for key in expected_hist_data:
        assert key in hist_output

    expected_global_attrs = [
        "flight_software_version",
        "pkts_file_name",
    ]
    for key in expected_global_attrs:
        assert key in hist_output._attrs

    de_output = glows_l1b_de(de_dataset, mock_conversion_table_dict)

    # From table 15 in the algorithm document
    expected_de_data = [
        # "unique_identifier", TODO: determine the best way to add this
        "imap_time_last_pps",
        "imap_time_next_pps",
        "glows_time_last_pps",
        "number_of_completed_spins",
        "filter_temperature",
        "hv_voltage",
        "spin_period",
        "spin_phase_at_next_pps",
        "de_flags",
        "direct_event_glows_times",
        "direct_event_pulse_lengths",
    ]

    for key in expected_de_data:
        assert key in de_output


@patch.object(
    HistogramL1B,
    "flag_uv_and_excluded",
    return_value=(np.zeros(3600, dtype=bool), np.zeros(3600, dtype=bool)),
)
@patch.object(HistogramL1B, "update_spice_parameters", autospec=True)
def test_generate_histogram_dataset(
    mock_spice_function,
    mock_flag_uv_and_excluded,
    hist_dataset,
    mock_ancillary_exclusions,
    mock_pipeline_settings,
    mock_conversion_table_dict,
):
    mock_spice_function.side_effect = mock_update_spice_parameters

    l1b_data = glows_l1b(
        hist_dataset,
        mock_ancillary_exclusions.excluded_regions,
        mock_ancillary_exclusions.uv_sources,
        mock_ancillary_exclusions.suspected_transients,
        mock_ancillary_exclusions.exclusions_by_instr_team,
        mock_pipeline_settings,
        mock_conversion_table_dict,
    )

    output_path = write_cdf(l1b_data)

    assert Path.exists(output_path)


def test_generate_de_dataset(
    de_dataset,
    mock_ancillary_exclusions,
    mock_pipeline_settings,
    mock_conversion_table_dict,
):
    l1b_data = glows_l1b_de(de_dataset, mock_conversion_table_dict)

    output_path = write_cdf(l1b_data)

    assert Path.exists(output_path)


@pytest.mark.external_kernel
@pytest.mark.usefixtures("use_fake_spin_data_for_time")
@patch("imap_processing.spice.geometry.imap_state")
def test_hist_spice_output(
    mock_imap_state,
    use_fake_spin_data_for_time,
    furnish_kernels,
    mock_ancillary_exclusions,
    mock_ancillary_parameters,
    mock_pipeline_settings,
):
    # Mock the imap_state function
    mock_imap_state.return_value = np.array(
        [
            [1.0, 2.0, 3.0, 0.1, 0.2, 0.3],  # Example position and velocity data
            [4.0, 5.0, 6.0, 0.4, 0.5, 0.6],
        ]
    )

    # Generate a fake spin data for time
    data_start_time = 504975600.125  # 2026-01-01T15:00:00.125
    use_fake_spin_data_for_time(data_start_time)
    params = {
        "histogram": np.zeros(3600),
        "seq_count_in_pkts_file": 0,
        "first_spin_id": 0,
        "last_spin_id": 0,
        "flags_set_onboard": 0,
        "is_generated_on_ground": 1,
        "number_of_spins_per_block": 1,
        "number_of_bins_per_histogram": 3600,
        "number_of_events": 0,
        "filter_temperature_average": 20.0,
        "filter_temperature_variance": 0.0,
        "hv_voltage_average": 1000.0,
        "hv_voltage_variance": 0.0,
        "spin_period_average": 10.0,
        "spin_period_variance": 0.0,
        "pulse_length_average": 50.0,
        "pulse_length_variance": 0.0,
        "imap_start_time": 504975603.125,
        "imap_time_offset": 200.0,
        "glows_start_time": 504975603.125,
        "glows_time_offset": 200.0,
        "ancillary_exclusions": mock_ancillary_exclusions,
        "ancillary_parameters": mock_ancillary_parameters,
        "pipeline_settings": PipelineSettings(
            mock_pipeline_settings.sel(
                epoch=mock_pipeline_settings.epoch[0], method="nearest"
            ),
        ),
    }

    kernels = [
        "naif0012.tls",
        "de440s.bsp",
        "imap_sclk_0000.tsc",
        "imap_130.tf",
        "imap_science_120.tf",
        "sim_1yr_imap_attitude.bc",
        "sim_1yr_imap_pointing_frame.bc",
    ]
    with furnish_kernels(kernels):
        hist_data = HistogramL1B(**params)

        day = met_to_datetime64(hist_data.imap_start_time)
        day_exclusions = mock_ancillary_exclusions.limit_by_day(day)

        uv_mask, region_mask = hist_data.flag_uv_and_excluded(day_exclusions)

        # Assert that all these variables are the correct shape:
        assert isinstance(hist_data.spin_period_ground_average, np.float64)
        assert isinstance(hist_data.spin_period_ground_std_dev, np.float64)
        assert isinstance(hist_data.position_angle_offset_average, np.float64)
        assert isinstance(hist_data.position_angle_offset_std_dev, np.float64)
        assert hist_data.spin_axis_orientation_std_dev.shape == (2,)
        assert hist_data.spin_axis_orientation_average.shape == (2,)
        assert hist_data.spacecraft_location_average.shape == (3,)
        assert hist_data.spacecraft_location_std_dev.shape == (3,)
        assert hist_data.spacecraft_velocity_average.shape == (3,)
        assert hist_data.spacecraft_velocity_std_dev.shape == (3,)
        assert uv_mask.shape == (3600,)
        # For 2 degree radius: 20 + 20 + 1(center) ≈ 41 bins.
        assert np.count_nonzero(uv_mask) == 41
        # Each individual excluded region center can only flag 0 or 1 bins
        # (since the 0.05° threshold is exactly half the 0.1° bin spacing.
        assert np.count_nonzero(region_mask) == 1

        # Test flag_from_mask_dataset using the fixture data
        instr_mask = hist_data.flag_from_mask_dataset(
            day_exclusions.exclusions_by_instr_team
        )
        assert instr_mask.shape == (3600,)
        assert np.count_nonzero(instr_mask) == 10

        # TODO: Maxine will validate actual data with GLOWS team
