name: "Documentation Build"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
- pull_request
- release

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[doc]

    - name: Check installed version
      # Run outside the checkout so cwd doesn't shadow site-packages
      working-directory: /tmp
      run: python -c "import imap_processing as m; assert m.__version__ != '0.0.0'"

    - name: Build documentation
      run: |
        # SPHINXOPTS="-W --keep-going" is used to turn warnings into errors
        # but keep going, so we don't fail on the first one.
        make -C docs html SPHINXOPTS="-W --keep-going"
